package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2015/4/15 �W�� 10:43:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AdmFunctionTypeDTO;

/**
 * Function generated by hbm2java
 */
public class AdmFunctionType extends DomainModelObject<String, AdmFunctionTypeDTO> {

	private String functionName;
	private String functionCode;
	private String functionDescription;
	private String functionUrl;
	private String status;
	private String parentFunctionId;
	private String functionCategory;
	private Integer functionOrder;
	

	public AdmFunctionType() {
	}

	public AdmFunctionType(String id) {
		this.id = id;
	}

	public AdmFunctionType(String functionName, String functionCode,
			String functionDescription, String functionUrl, String status,
			String parentFunctionId, String functionCategory,
			Integer functionOrder) {
		super();
		this.functionName = functionName;
		this.functionCode = functionCode;
		this.functionDescription = functionDescription;
		this.functionUrl = functionUrl;
		this.status = status;
		this.parentFunctionId = parentFunctionId;
		this.functionCategory = functionCategory;
		this.functionOrder = functionOrder;
	}

	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getFunctionCode() {
		return this.functionCode;
	}

	public void setFunctionCode(String functionCode) {
		this.functionCode = functionCode;
	}

	public String getFunctionDescription() {
		return this.functionDescription;
	}

	public void setFunctionDescription(String functionDescription) {
		this.functionDescription = functionDescription;
	}

	public String getFunctionUrl() {
		return this.functionUrl;
	}

	public void setFunctionUrl(String functionUrl) {
		this.functionUrl = functionUrl;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getParentFunctionId() {
		return this.parentFunctionId;
	}

	public void setParentFunctionId(String parentFunctionId) {
		this.parentFunctionId = parentFunctionId;
	}

	public String getFunctionCategory() {
		return this.functionCategory;
	}

	public void setFunctionCategory(String functionCategory) {
		this.functionCategory = functionCategory;
	}

	public Integer getFunctionOrder() {
		return this.functionOrder;
	}

	public void setFunctionOrder(Integer functionOrder) {
		this.functionOrder = functionOrder;
	}

}
