package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;
import cafe.identity.bean.dto.PermissionDTO;


// Generated 2015/4/29 �U�� 03:53:36 by Hibernate Tools 3.4.0.CR1

/**
 * Permission generated by hbm2java
 */
public class AdmPermission extends DomainModelObject<String, PermissionDTO> {

	private AdmFunctionType function;
	private String accessRight;

	public AdmPermission() {
	}

	public AdmPermission(String id) {
		this.id = id;
	}

	public AdmPermission(String id, AdmFunctionType function, String accessRight) {
		this.id = id;
		this.function = function;
		this.accessRight = accessRight;
	}

	public AdmFunctionType getFunction() {
		return this.function;
	}

	public void setFunction(AdmFunctionType function) {
		this.function = function;
	}

	public String getAccessRight() {
		return this.accessRight;
	}

	public void setAccessRight(String accessRight) {
		this.accessRight = accessRight;
	}

}
