package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2015/4/29 �U�� 03:53:36 by Hibernate Tools 3.4.0.CR1

/**
 * RolePermissionId generated by hbm2java
 */
public class AdmRolePermissionId extends CompositeIdentifier {

	private String roleId;
	private String permissionId;

	public AdmRolePermissionId() {
	}

	public AdmRolePermissionId(String roleId, String permissionId) {
		this.roleId = roleId;
		this.permissionId = permissionId;
	}


	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdmRolePermissionId))
			return false;
		AdmRolePermissionId castOther = (AdmRolePermissionId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& ((this.getPermissionId() == castOther.getPermissionId()) || (this
						.getPermissionId() != null
						&& castOther.getPermissionId() != null && this
						.getPermissionId().equals(castOther.getPermissionId())));
	}

}
