package com.cybersoft4u.xian.iatoms.services.dmo;

import java.sql.Timestamp;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.RolePermissionDTO;


// Generated 2015/4/29 �U�� 03:53:36 by Hibernate Tools 3.4.0.CR1

/**
 * RolePermission generated by hbm2java
 */
public class AdmRolePermission extends DomainModelObject<AdmRolePermissionId, RolePermissionDTO> {

	private String updatedById;
	private String updatedByName;
	private Timestamp updatedDate;

	public AdmRolePermission() {
	}

	public AdmRolePermission(AdmRolePermissionId id) {
		this.id = id;
	}
	
	public AdmRolePermission(AdmRolePermissionId id, String updatedById, String updatedByName, Timestamp updatedDate) {
		this.id = id;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
	}

	public String getUpdatedById() {
		return this.updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Timestamp getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Timestamp updatedDate) {
		this.updatedDate = updatedDate;
	}
}
