package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/3/29 �U�� 05:33:29 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AdmUserDTO;


/**
 * AdmUser generated by hbm2java
 */
public class AdmUser extends DomainModelObject<String,AdmUserDTO> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3390384388247732007L;
	private String userId;
	private String account;
	private String companyId;
	private String deptCode;
	private String password;
	private String cname;
	private String ename;
	private String tel;
	private String mobile;
	private String email;
	private String managerEmail;
	private String userDesc;
	private Integer retry;
	private String status;
	private String dataAcl = "N";
	private Timestamp lastLoginDate;
	private Date changePwdDate;
	private String createdById;
	private String createdByName;
	private Timestamp createdDate;
	private String updatedById;
	private String updatedByName;
	private Timestamp updatedDate;
	private String deleted = "N";
	private String resetPwd = "N";

	public AdmUser() {
	}

	public AdmUser(String userId, String account, String deleted) {
		this.userId = userId;
		this.account = account;
		this.deleted = deleted;
	}

	public AdmUser(String userId, String account, String companyId, String deptCode, String password,
			String cname, String ename, String tel, String mobile, String email, String managerEmail, String userDesc,
			Integer retry, String status, String dataAcl, Timestamp lastLoginDate, Date changePwdDate, String createdById,
			String createdByName, Timestamp createdDate, String updatedById, String updatedByName, Timestamp updatedDate,
			String deleted,String resetPwd) {
		this.userId = userId;
		this.account = account;
		this.companyId = companyId;
		this.deptCode = deptCode;
		this.password = password;
		this.cname = cname;
		this.ename = ename;
		this.tel = tel;
		this.mobile = mobile;
		this.email = email;
		this.managerEmail = managerEmail;
		this.userDesc = userDesc;
		this.retry = retry;
		this.status = status;
		this.dataAcl = dataAcl;
		this.lastLoginDate = lastLoginDate;
		this.changePwdDate = changePwdDate;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.deleted = deleted;
		this.resetPwd = resetPwd;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getManagerEmail() {
		return this.managerEmail;
	}

	public void setManagerEmail(String managerEmail) {
		this.managerEmail = managerEmail;
	}

	public String getUserDesc() {
		return this.userDesc;
	}

	public void setUserDesc(String userDesc) {
		this.userDesc = userDesc;
	}

	public Integer getRetry() {
		return this.retry;
	}

	public void setRetry(Integer retry) {
		this.retry = retry;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDataAcl() {
		return this.dataAcl;
	}

	public void setDataAcl(String dataAcl) {
		this.dataAcl = dataAcl;
	}

	public Timestamp getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Timestamp lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public Date getChangePwdDate() {
		return this.changePwdDate;
	}

	public void setChangePwdDate(Date changePwdDate) {
		this.changePwdDate = changePwdDate;
	}

	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Timestamp getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedById() {
		return this.updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Timestamp getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Timestamp updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	/**
	 * @return the resetPwd
	 */
	public String getResetPwd() {
		return resetPwd;
	}

	/**
	 * @param resetPwd the resetPwd to set
	 */
	public void setResetPwd(String resetPwd) {
		this.resetPwd = resetPwd;
	}
}