package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/3/30 �U�� 01:51:49 by Hibernate Tools 3.4.0.CR1

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AdmUserRoleDTO;


/**
 * AdmUserRole generated by hbm2java
 */
public class AdmUserRole extends DomainModelObject<AdmUserRoleId,AdmUserRoleDTO> {

	private AdmUserRoleId id;

	public AdmUserRole() {
	}

	public AdmUserRole(AdmUserRoleId id) {
		this.id = id;
	}

	public AdmUserRoleId getId() {
		return this.id;
	}

	public void setId(AdmUserRoleId id) {
		this.id = id;
	}

}
