package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/8/19 �W�� 11:46:02 by Hibernate Tools 3.4.0.CR1

import cafe.core.bean.CompositeIdentifier;

/**
 * AdmUserWarehouseId generated by hbm2java
 */
public class AdmUserWarehouseId extends CompositeIdentifier {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1237881849032984132L;
	private String userId;
	private String warehouseId;

	public AdmUserWarehouseId() {
	}

	public AdmUserWarehouseId(String userId, String warehouseId) {
		this.userId = userId;
		this.warehouseId = warehouseId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdmUserWarehouseId))
			return false;
		AdmUserWarehouseId castOther = (AdmUserWarehouseId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getWarehouseId() == castOther.getWarehouseId()) || (this
						.getWarehouseId() != null
						&& castOther.getWarehouseId() != null && this
						.getWarehouseId().equals(castOther.getWarehouseId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getWarehouseId() == null ? 0 : this.getWarehouseId()
						.hashCode());
		return result;
	}

}
