package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/8/19 �W�� 11:46:02 by Hibernate Tools 3.4.0.CR1

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AdmUserWarehouseDTO;

/**
 * AdmUserWarehouse generated by hbm2java
 */
public class AdmUserWarehouse extends DomainModelObject<AdmUserWarehouseId,AdmUserWarehouseDTO> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3901638033986371079L;
	private AdmUserWarehouseId id;

	public AdmUserWarehouse() {
	}

	public AdmUserWarehouse(AdmUserWarehouseId id) {
		this.id = id;
	}

	public AdmUserWarehouseId getId() {
		return this.id;
	}

	public void setId(AdmUserWarehouseId id) {
		this.id = id;
	}

}
