package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2016/8/19 �W�� 11:46:02 by Hibernate Tools 3.4.0.CR1

/**
 * BimCompanyTypeId generated by hbm2java
 */
public class BimCompanyTypeId extends CompositeIdentifier {

	private String companyId;
	private String companyType;

	public BimCompanyTypeId() {
	}

	public BimCompanyTypeId(String companyId, String companyType) {
		this.companyId = companyId;
		this.companyType = companyType;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BimCompanyTypeId))
			return false;
		BimCompanyTypeId castOther = (BimCompanyTypeId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this
				.getCompanyId() != null && castOther.getCompanyId() != null && this
				.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getCompanyType() == castOther.getCompanyType()) || (this
						.getCompanyType() != null
						&& castOther.getCompanyType() != null && this
						.getCompanyType().equals(castOther.getCompanyType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37
				* result
				+ (getCompanyType() == null ? 0 : this.getCompanyType()
						.hashCode());
		return result;
	}

}
