package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2016/6/3 �U�� 01:30:43 by Hibernate Tools 3.4.0.CR1

/**
 * ContractAssetId generated by hbm2java
 */
public class BimContractAssetId extends CompositeIdentifier {

	private String contractId;
	private String assetTypeId;

	public BimContractAssetId() {
	}

	public BimContractAssetId(String contractId, String assetTypeId) {
		this.contractId = contractId;
		this.assetTypeId = assetTypeId;
	}

	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getAssetTypeId() {
		return this.assetTypeId;
	}

	public void setAssetTypeId(String assetTypeId) {
		this.assetTypeId = assetTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BimContractAssetId))
			return false;
		BimContractAssetId castOther = (BimContractAssetId) other;

		return ((this.getContractId() == castOther.getContractId()) || (this
				.getContractId() != null && castOther.getContractId() != null && this
				.getContractId().equals(castOther.getContractId())))
				&& ((this.getAssetTypeId() == castOther.getAssetTypeId()) || (this
						.getAssetTypeId() != null
						&& castOther.getAssetTypeId() != null && this
						.getAssetTypeId().equals(castOther.getAssetTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getContractId() == null ? 0 : this.getContractId()
						.hashCode());
		result = 37
				* result
				+ (getAssetTypeId() == null ? 0 : this.getAssetTypeId()
						.hashCode());
		return result;
	}

}
