package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2016/8/5 �U�� 01:28:31 by Hibernate Tools 3.4.0.CR1

/**
 * BimContractVendorId generated by hbm2java
 */
public class BimContractVendorId extends CompositeIdentifier {

	private String contractId;
	private String companyId;

	public BimContractVendorId() {
	}

	public BimContractVendorId(String contractId, String companyId) {
		this.contractId = contractId;
		this.companyId = companyId;
	}

	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BimContractVendorId))
			return false;
		BimContractVendorId castOther = (BimContractVendorId) other;

		return ((this.getContractId() == castOther.getContractId()) || (this
				.getContractId() != null && castOther.getContractId() != null && this
				.getContractId().equals(castOther.getContractId())))
				&& ((this.getCompanyId() == castOther.getCompanyId()) || (this
						.getCompanyId() != null
						&& castOther.getCompanyId() != null && this
						.getCompanyId().equals(castOther.getCompanyId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getContractId() == null ? 0 : this.getContractId()
						.hashCode());
		result = 37 * result
				+ (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		return result;
	}

}
