package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.BimContractTypeDTO;

// Generated 2016/8/10 �U�� 01:29:28 by Hibernate Tools 3.4.0.CR1

/**
 * BimContractType generated by hbm2java
 */
public class BimContractType extends DomainModelObject<BimContractTypeId,BimContractTypeDTO> {

	private BimContractTypeId id;

	public BimContractType() {
	}

	public BimContractType(BimContractTypeId id) {
		this.id = id;
	}

	public BimContractTypeId getId() {
		return this.id;
	}

	public void setId(BimContractTypeId id) {
		this.id = id;
	}

}
