package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.BimContractVendorDTO;

// Generated 2016/8/5 �U�� 01:28:31 by Hibernate Tools 3.4.0.CR1

/**
 * BimContractVendor generated by hbm2java
 */
public class BimContractVendor extends  DomainModelObject<BimContractVendorId,BimContractVendorDTO> {

	private BimContractVendorId id;
	private BimContract bimContract;

	public BimContractVendor() {
	}

	public BimContractVendor(BimContractVendorId id, BimContract bimContract) {
		this.id = id;
		this.bimContract = bimContract;
	}

	public BimContractVendorId getId() {
		return this.id;
	}

	public void setId(BimContractVendorId id) {
		this.id = id;
	}

	public BimContract getBimContract() {
		return this.bimContract;
	}

	public void setBimContract(BimContract bimContract) {
		this.bimContract = bimContract;
	}

}
