package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.ReportSettingDetailDTO;

// Generated 2016/8/5 �U�� 01:28:31 by Hibernate Tools 3.4.0.CR1

/**
 * BimReportSettingDetail generated by hbm2java
 */
public class BimReportSettingDetail extends DomainModelObject<BimReportSettingDetailId,ReportSettingDetailDTO> {

	private BimReportSettingDetailId id;
	private BimReportSetting bimReportSetting;

	public BimReportSettingDetail() {
	}

	public BimReportSettingDetail(BimReportSettingDetailId id,
			BimReportSetting bimReportSetting) {
		this.id = id;
		this.bimReportSetting = bimReportSetting;
	}

	public BimReportSettingDetailId getId() {
		return this.id;
	}

	public void setId(BimReportSettingDetailId id) {
		this.id = id;
	}

	public BimReportSetting getBimReportSetting() {
		return this.bimReportSetting;
	}

	public void setBimReportSetting(BimReportSetting bimReportSetting) {
		this.bimReportSetting = bimReportSetting;
	}

}
