package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.CaseDetailDTO;

import cafe.workflow.dmo.AbstractCaseDetail;

/**
 * CaseDetail generated by hbm2java
 */
public class CaseDetail extends AbstractCaseDetail<CaseDetailDTO> {

	private String caseType;

	public CaseDetail() {
	}

	public CaseDetail(String id, String caseType, String processId) {
		this.id = id;
		this.caseType = caseType;
		this.setProcessId(processId);
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}
}
