package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/6/3 �U�� 01:30:43 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmAssetTransInfoDTO;

/**
 * AssetTransInfo generated by hbm2java
 */
public class DmmAssetTransInfo extends DomainModelObject<String, DmmAssetTransInfoDTO> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -9095628447167737476L;
	
	private String assetTransId;
	private String fromWarehouseId;
	private String toWarehouseId;
	private String comment;
	private String isListDone = "N";
	private String isTransDone = "N";
	private String isBack = "N";
	private String createdById;
	private String createdByName;
	private Timestamp createdDate;
	private String updatedById;
	private String updatedByName;
	private Timestamp updatedDate;
	private String noticeUserId;
	private String transOutUserId;
	private String transOutUserName;
	private Timestamp transOutDate;
	private String acceptanceUserId;
	private String acceptanceUserName;
	private Timestamp acceptanceDate;
	private String cancelUserId;
	private String cancelUserName;
	private Timestamp cancelDate;
	private String isCancel = "N";

	/**
	 * Constructor:無參構造函數
	 */
	public DmmAssetTransInfo() {
	}

	public DmmAssetTransInfo(String assetTransId, String fromWarehouseId,
			String toWarehouseId, String isListDone, String isTransDone,
			String isBack) {
		this.assetTransId = assetTransId;
		this.fromWarehouseId = fromWarehouseId;
		this.toWarehouseId = toWarehouseId;
		this.isListDone = isListDone;
		this.isTransDone = isTransDone;
		this.isBack = isBack;
	}

	public DmmAssetTransInfo(String assetTransId, 
			String fromWarehouseId, String toWarehouseId, String comment,
			String isListDone, String isTransDone, String isBack, String createdById,
			String createdByName, Timestamp createdDate, String updatedById,
			String updatedByName, Timestamp updatedDate,
			String noticeUserId, String transOutUserId,
			String transOutUserName, Timestamp transOutDate,
			String acceptanceUserId, String acceptanceUserName,
			Timestamp acceptanceDate, String cancelUserId, String cancelUserName,
			Timestamp cancelDate) {
		this.assetTransId = assetTransId;
		this.fromWarehouseId = fromWarehouseId;
		this.toWarehouseId = toWarehouseId;
		this.comment = comment;
		this.isListDone = isListDone;
		this.isTransDone = isTransDone;
		this.isBack = isBack;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.noticeUserId = noticeUserId;
		this.transOutUserId = transOutUserId;
		this.transOutUserName = transOutUserName;
		this.transOutDate = transOutDate;
		this.acceptanceUserId = acceptanceUserId;
		this.acceptanceUserName = acceptanceUserName;
		this.acceptanceDate = acceptanceDate;
		this.cancelUserId = cancelUserId;
		this.cancelUserName = cancelUserName;
		this.cancelDate = cancelDate;
	}

	/**
	 * @return the assetTransId
	 */
	public String getAssetTransId() {
		return assetTransId;
	}

	/**
	 * @param assetTransId the assetTransId to set
	 */
	public void setAssetTransId(String assetTransId) {
		this.assetTransId = assetTransId;
	}

	/**
	 * @return the fromWarehouseId
	 */
	public String getFromWarehouseId() {
		return fromWarehouseId;
	}

	/**
	 * @param fromWarehouseId the fromWarehouseId to set
	 */
	public void setFromWarehouseId(String fromWarehouseId) {
		this.fromWarehouseId = fromWarehouseId;
	}

	/**
	 * @return the toWarehouseId
	 */
	public String getToWarehouseId() {
		return toWarehouseId;
	}

	/**
	 * @param toWarehouseId the toWarehouseId to set
	 */
	public void setToWarehouseId(String toWarehouseId) {
		this.toWarehouseId = toWarehouseId;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the isListDone
	 */
	public String getIsListDone() {
		return isListDone;
	}

	/**
	 * @param isListDone the isListDone to set
	 */
	public void setIsListDone(String isListDone) {
		this.isListDone = isListDone;
	}

	/**
	 * @return the isTransDone
	 */
	public String getIsTransDone() {
		return isTransDone;
	}

	/**
	 * @param isTransDone the isTransDone to set
	 */
	public void setIsTransDone(String isTransDone) {
		this.isTransDone = isTransDone;
	}

	/**
	 * @return the isBack
	 */
	public String getIsBack() {
		return isBack;
	}

	/**
	 * @param isBack the isBack to set
	 */
	public void setIsBack(String isBack) {
		this.isBack = isBack;
	}

	/**
	 * @return the createdById
	 */
	public String getCreatedById() {
		return createdById;
	}

	/**
	 * @param createdById the createdById to set
	 */
	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	/**
	 * @return the createdByName
	 */
	public String getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public Timestamp getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Timestamp getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Timestamp updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getNoticeUserId() {
		return this.noticeUserId;
	}

	public void setNoticeUserId(String noticeUserId) {
		this.noticeUserId = noticeUserId;
	}

	public String getTransOutUserId() {
		return this.transOutUserId;
	}

	public void setTransOutUserId(String transOutUserId) {
		this.transOutUserId = transOutUserId;
	}

	public String getTransOutUserName() {
		return this.transOutUserName;
	}

	public void setTransOutUserName(String transOutUserName) {
		this.transOutUserName = transOutUserName;
	}

	public Timestamp getTransOutDate() {
		return this.transOutDate;
	}

	public void setTransOutDate(Timestamp transOutDate) {
		this.transOutDate = transOutDate;
	}

	public String getAcceptanceUserId() {
		return this.acceptanceUserId;
	}

	public void setAcceptanceUserId(String acceptanceUserId) {
		this.acceptanceUserId = acceptanceUserId;
	}

	public String getAcceptanceUserName() {
		return this.acceptanceUserName;
	}

	public void setAcceptanceUserName(String acceptanceUserName) {
		this.acceptanceUserName = acceptanceUserName;
	}

	public Timestamp getAcceptanceDate() {
		return this.acceptanceDate;
	}

	public void setAcceptanceDate(Timestamp acceptanceDate) {
		this.acceptanceDate = acceptanceDate;
	}

	public String getCancelUserId() {
		return this.cancelUserId;
	}

	public void setCancelUserId(String cancelUserId) {
		this.cancelUserId = cancelUserId;
	}

	public String getCancelUserName() {
		return this.cancelUserName;
	}

	public void setCancelUserName(String cancelUserName) {
		this.cancelUserName = cancelUserName;
	}

	public Timestamp getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Timestamp cancelDate) {
		this.cancelDate = cancelDate;
	}

	public String getIsCancel() {
		return isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}
}