package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/6/3 �U�� 01:30:43 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AssetInInfoDTO;

/**
 * AssetInInfo generated by hbm2java
 */
public class DmmAssetInInfo extends DomainModelObject<String, AssetInInfoDTO> {

	private String assetInId;
	private String assetTypeId;
	private String contractId;
	private String warehouseId;
	private String companyId;
	private String maType;
	private String customerId;
	private String owner;
	private String userId;
	private String keeperName;
	private Date cyberApprovedDate;
	private Date customerApproveDate;
	private String comment;
	private String createdById;
	private String createdByName;
	private Timestamp createdDate;
	private String updatedById;
	private String updatedByName;
	private Timestamp updatedDate;
	private String isDone = "N";
	private Date customerWarrantyDate;
	private Date factoryWarrantyDate;
	private String isFinished = "N";
	private String assetModel;
	private String brand;

	public DmmAssetInInfo() {
	}

	public DmmAssetInInfo(String assetInId) {
		this.assetInId = assetInId;
	}

	public DmmAssetInInfo(String assetInId, String assetTypeId,
			String contractId, String warehouseId,
			String companyId, String maType, String customerId,
			String owner, String userId, String keeperName,
			Timestamp cyberApprovedDate,
			Timestamp customerApproveDate, String comment, String createdById,
			String createdByName, Timestamp createdDate, String updatedById,
			String updatedByName, Timestamp updatedDate, String isDone,
			Timestamp customerWarrantyDate, Timestamp factoryWarrantyDate,
			String isFinished,String assetModel,
			String brand) {
		this.assetInId = assetInId;
		this.assetTypeId = assetTypeId;
		this.contractId = contractId;
		this.warehouseId = warehouseId;
		this.companyId = companyId;
		this.maType = maType;
		this.customerId = customerId;
		this.owner = owner;
		this.userId = userId;
		this.keeperName = keeperName;
		this.cyberApprovedDate = cyberApprovedDate;
		this.customerApproveDate = customerApproveDate;
		this.comment = comment;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.isDone = isDone;
		this.customerWarrantyDate = customerWarrantyDate;
		this.factoryWarrantyDate = factoryWarrantyDate;
		this.isFinished = isFinished;
		this.assetModel = assetModel;
		this.brand = brand;
	}

	/**
	 * @return the assetInId
	 */
	public String getAssetInId() {
		return assetInId;
	}

	/**
	 * @param assetInId the assetInId to set
	 */
	public void setAssetInId(String assetInId) {
		this.assetInId = assetInId;
	}

	/**
	 * @return the assetTypeId
	 */
	public String getAssetTypeId() {
		return assetTypeId;
	}

	/**
	 * @param assetTypeId the assetTypeId to set
	 */
	public void setAssetTypeId(String assetTypeId) {
		this.assetTypeId = assetTypeId;
	}

	/**
	 * @return the contractId
	 */
	public String getContractId() {
		return contractId;
	}

	/**
	 * @param contractId the contractId to set
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	/**
	 * @return the warehouseId
	 */
	public String getWarehouseId() {
		return warehouseId;
	}

	/**
	 * @param warehouseId the warehouseId to set
	 */
	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	/**
	 * @return the companyId
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * @param companyId the companyId to set
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * @return the maType
	 */
	public String getMaType() {
		return maType;
	}

	/**
	 * @param maType the maType to set
	 */
	public void setMaType(String maType) {
		this.maType = maType;
	}

	/**
	 * @return the customerId
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * @param customerId the customerId to set
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	/**
	 * @return the owner
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * @param owner the owner to set
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * @return the keeperName
	 */
	public String getKeeperName() {
		return keeperName;
	}

	/**
	 * @param keeperName the keeperName to set
	 */
	public void setKeeperName(String keeperName) {
		this.keeperName = keeperName;
	}

	/**
	 * @return the cyberApprovedDate
	 */
	public Date getCyberApprovedDate() {
		return cyberApprovedDate;
	}

	/**
	 * @param cyberApprovedDate the cyberApprovedDate to set
	 */
	public void setCyberApprovedDate(Date cyberApprovedDate) {
		this.cyberApprovedDate = cyberApprovedDate;
	}

	/**
	 * @return the customerApproveDate
	 */
	public Date getCustomerApproveDate() {
		return customerApproveDate;
	}

	/**
	 * @param customerApproveDate the customerApproveDate to set
	 */
	public void setCustomerApproveDate(Date customerApproveDate) {
		this.customerApproveDate = customerApproveDate;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the createdById
	 */
	public String getCreatedById() {
		return createdById;
	}

	/**
	 * @param createdById the createdById to set
	 */
	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	/**
	 * @return the createdByName
	 */
	public String getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public Timestamp getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Timestamp getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Timestamp updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the isDone
	 */
	public String getIsDone() {
		return isDone;
	}

	/**
	 * @param isDone the isDone to set
	 */
	public void setIsDone(String isDone) {
		this.isDone = isDone;
	}

	/**
	 * @return the customerWarrantyDate
	 */
	public Date getCustomerWarrantyDate() {
		return customerWarrantyDate;
	}

	/**
	 * @param customerWarrantyDate the customerWarrantyDate to set
	 */
	public void setCustomerWarrantyDate(Date customerWarrantyDate) {
		this.customerWarrantyDate = customerWarrantyDate;
	}

	/**
	 * @return the factoryWarrantyDate
	 */
	public Date getFactoryWarrantyDate() {
		return factoryWarrantyDate;
	}

	/**
	 * @param factoryWarrantyDate the factoryWarrantyDate to set
	 */
	public void setFactoryWarrantyDate(Date factoryWarrantyDate) {
		this.factoryWarrantyDate = factoryWarrantyDate;
	}

	/**
	 * @return the isFinished
	 */
	public String getIsFinished() {
		return isFinished;
	}

	/**
	 * @param isFinished the isFinished to set
	 */
	public void setIsFinished(String isFinished) {
		this.isFinished = isFinished;
	}

	/**
	 * @return the assetModel
	 */
	public String getAssetModel() {
		return assetModel;
	}

	/**
	 * @param assetModel the assetModel to set
	 */
	public void setAssetModel(String assetModel) {
		this.assetModel = assetModel;
	}

	/**
	 * @return the brand
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * @param brand the brand to set
	 */
	public void setBrand(String brand) {
		this.brand = brand;
	}
	
}