package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/6/3 �U�� 01:30:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.AssetInListDTO;

/**
 * AssetInList generated by hbm2java
 */
public class DmmAssetInListHistory extends DomainModelObject<String,AssetInListDTO> {

	private String serialNumber;
	private String assetInId;
	private String propertyId;
	private String isChecked = "N";
	private String isCustomerChecked = "N";
	private Date checkedDate;
	private Date customerCheckedDate;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;

	public DmmAssetInListHistory() {
	}

	public DmmAssetInListHistory(String id) {
		this.id = id;
	}

	public DmmAssetInListHistory(String id, String assetInId,
			String serialNumber, String propertyId, String isChecked,
			String isCustomerChecked, String updatedById, String updatedByName,
			Date updatedDate) {
		this.id = id;
		this.assetInId = assetInId;
		this.serialNumber = serialNumber;
		this.propertyId = propertyId;
		this.isChecked = isChecked;
		this.isCustomerChecked = isCustomerChecked;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the serialNumber
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * @param serialNumber the serialNumber to set
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	/**
	 * @return the assetInId
	 */
	public String getAssetInId() {
		return assetInId;
	}

	/**
	 * @param assetInId the assetInId to set
	 */
	public void setAssetInId(String assetInId) {
		this.assetInId = assetInId;
	}

	/**
	 * @return the propertyId
	 */
	public String getPropertyId() {
		return propertyId;
	}

	/**
	 * @param propertyId the propertyId to set
	 */
	public void setPropertyId(String propertyId) {
		this.propertyId = propertyId;
	}

	/**
	 * @return the isChecked
	 */
	public String getIsChecked() {
		return isChecked;
	}

	/**
	 * @param isChecked the isChecked to set
	 */
	public void setIsChecked(String isChecked) {
		this.isChecked = isChecked;
	}

	/**
	 * @return the isCustomerChecked
	 */
	public String getIsCustomerChecked() {
		return isCustomerChecked;
	}

	/**
	 * @param isCustomerChecked the isCustomerChecked to set
	 */
	public void setIsCustomerChecked(String isCustomerChecked) {
		this.isCustomerChecked = isCustomerChecked;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the checkedDate
	 */
	public Date getCheckedDate() {
		return checkedDate;
	}

	/**
	 * @param checkedDate the checkedDate to set
	 */
	public void setCheckedDate(Date checkedDate) {
		this.checkedDate = checkedDate;
	}

	/**
	 * @return the customerCheckedDate
	 */
	public Date getCustomerCheckedDate() {
		return customerCheckedDate;
	}

	/**
	 * @param customerCheckedDate the customerCheckedDate to set
	 */
	public void setCustomerCheckedDate(Date customerCheckedDate) {
		this.customerCheckedDate = customerCheckedDate;
	}
	
}
