package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryHistoryMonthlyDescDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryMonthlyDesc generated by hbm2java
 */
public class DmmRepositoryHistoryMonthlyDesc extends DomainModelObject<DmmRepositoryHistoryMonthlyDescId,DmmRepositoryHistoryMonthlyDescDTO> {

	private DmmRepositoryHistoryMonthlyDescId id;

	public DmmRepositoryHistoryMonthlyDesc() {
	}

	public DmmRepositoryHistoryMonthlyDesc(DmmRepositoryHistoryMonthlyDescId id) {
		this.id = id;
	}

	public DmmRepositoryHistoryMonthlyDescId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryHistoryMonthlyDescId id) {
		this.id = id;
	}

}
