package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryMonthlyId generated by hbm2java
 */
public class DmmRepositoryHistoryMonthlyId extends CompositeIdentifier {

	private String monthYear;
	private String assetId;

	public DmmRepositoryHistoryMonthlyId() {
	}

	public DmmRepositoryHistoryMonthlyId(String monthYear, String assetId) {
		this.monthYear = monthYear;
		this.assetId = assetId;
	}

	public String getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}


	/**
	 * @return the assetId
	 */
	public String getAssetId() {
		return assetId;
	}

	/**
	 * @param assetId the assetId to set
	 */
	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryHistoryMonthlyId))
			return false;
		DmmRepositoryHistoryMonthlyId castOther = (DmmRepositoryHistoryMonthlyId) other;

		return ((this.getMonthYear() == castOther.getMonthYear()) || (this
				.getMonthYear() != null && castOther.getMonthYear() != null && this
				.getMonthYear().equals(castOther.getMonthYear())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null
						&& castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMonthYear() == null ? 0 : this.getMonthYear().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		return result;
	}

}
