package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryHistoryMonthlyComDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryMonthlyCom generated by hbm2java
 */
public class DmmRepositoryHistoryMonthlyCom extends DomainModelObject<DmmRepositoryHistoryMonthlyComId,DmmRepositoryHistoryMonthlyComDTO> {

	private DmmRepositoryHistoryMonthlyComId id;

	public DmmRepositoryHistoryMonthlyCom() {
	}

	public DmmRepositoryHistoryMonthlyCom(DmmRepositoryHistoryMonthlyComId id) {
		this.id = id;
	}

	public DmmRepositoryHistoryMonthlyComId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryHistoryMonthlyComId id) {
		this.id = id;
	}

}
