package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryDescId generated by hbm2java
 */
public class DmmRepositoryHistoryDescId extends CompositeIdentifier {

	private String historyId;
	private String faultDescription;

	public DmmRepositoryHistoryDescId() {
	}

	public DmmRepositoryHistoryDescId(String historyId, String faultDescription) {
		this.historyId = historyId;
		this.faultDescription = faultDescription;
	}

	public String getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(String historyId) {
		this.historyId = historyId;
	}

	public String getFaultDescription() {
		return this.faultDescription;
	}

	public void setFaultDescription(String faultDescription) {
		this.faultDescription = faultDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryHistoryDescId))
			return false;
		DmmRepositoryHistoryDescId castOther = (DmmRepositoryHistoryDescId) other;

		return ((this.getHistoryId() == castOther.getHistoryId()) || (this
				.getHistoryId() != null && castOther.getHistoryId() != null && this
				.getHistoryId().equals(castOther.getHistoryId())))
				&& ((this.getFaultDescription() == castOther
						.getFaultDescription()) || (this.getFaultDescription() != null
						&& castOther.getFaultDescription() != null && this
						.getFaultDescription().equals(
								castOther.getFaultDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHistoryId() == null ? 0 : this.getHistoryId().hashCode());
		result = 37
				* result
				+ (getFaultDescription() == null ? 0 : this
						.getFaultDescription().hashCode());
		return result;
	}

}
