package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryFaultCom generated by hbm2java
 */
public class DmmRepositoryFaultCom extends DomainModelObject<DmmRepositoryFaultComId,DmmRepositoryDTO> {

	private DmmRepositoryFaultComId id;

	public DmmRepositoryFaultCom() {
	}

	public DmmRepositoryFaultCom(DmmRepositoryFaultComId id) {
		this.id = id;
	}

	public DmmRepositoryFaultComId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryFaultComId id) {
		this.id = id;
	}

}
