package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryFaultDescDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryFaultDesc generated by hbm2java
 */
public class DmmRepositoryFaultDesc extends DomainModelObject<DmmRepositoryFaultDescId,DmmRepositoryFaultDescDTO> {

	private DmmRepositoryFaultDescId id;

	public DmmRepositoryFaultDesc() {
	}

	public DmmRepositoryFaultDesc(DmmRepositoryFaultDescId id) {
		this.id = id;
	}

	public DmmRepositoryFaultDescId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryFaultDescId id) {
		this.id = id;
	}

}
