package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryMonthlyDescId generated by hbm2java
 */
public class DmmRepositoryHistoryMonthlyDescId extends CompositeIdentifier {

	private String monthYear;
	private String assetId;
	private String faultDescription;

	public DmmRepositoryHistoryMonthlyDescId() {
	}

	public DmmRepositoryHistoryMonthlyDescId(String monthYear,
			String assetId, String faultDescription) {
		this.monthYear = monthYear;
		this.assetId = assetId;
		this.faultDescription = faultDescription;
	}

	public String getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}

	

	/**
	 * @return the assetId
	 */
	public String getAssetId() {
		return assetId;
	}

	/**
	 * @param assetId the assetId to set
	 */
	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getFaultDescription() {
		return this.faultDescription;
	}

	public void setFaultDescription(String faultDescription) {
		this.faultDescription = faultDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryHistoryMonthlyDescId))
			return false;
		DmmRepositoryHistoryMonthlyDescId castOther = (DmmRepositoryHistoryMonthlyDescId) other;

		return ((this.getMonthYear() == castOther.getMonthYear()) || (this
				.getMonthYear() != null && castOther.getMonthYear() != null && this
				.getMonthYear().equals(castOther.getMonthYear())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null
						&& castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getFaultDescription() == castOther
						.getFaultDescription()) || (this.getFaultDescription() != null
						&& castOther.getFaultDescription() != null && this
						.getFaultDescription().equals(
								castOther.getFaultDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMonthYear() == null ? 0 : this.getMonthYear().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37
				* result
				+ (getFaultDescription() == null ? 0 : this
						.getFaultDescription().hashCode());
		return result;
	}

}
