package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryHistoryDescDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryDesc generated by hbm2java
 */
public class DmmRepositoryHistoryDesc extends DomainModelObject<DmmRepositoryHistoryDescId,DmmRepositoryHistoryDescDTO> {

	private DmmRepositoryHistoryDescId id;

	public DmmRepositoryHistoryDesc() {
	}

	public DmmRepositoryHistoryDesc(DmmRepositoryHistoryDescId id) {
		this.id = id;
	}

	public DmmRepositoryHistoryDescId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryHistoryDescId id) {
		this.id = id;
	}

}
