package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.DmmRepositoryHistoryCommDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryComm generated by hbm2java
 */
public class DmmRepositoryHistoryComm extends DomainModelObject<DmmRepositoryHistoryCommId,DmmRepositoryHistoryCommDTO> {

	private DmmRepositoryHistoryCommId id;

	public DmmRepositoryHistoryComm() {
	}

	public DmmRepositoryHistoryComm(DmmRepositoryHistoryCommId id) {
		this.id = id;
	}

	public DmmRepositoryHistoryCommId getId() {
		return this.id;
	}

	public void setId(DmmRepositoryHistoryCommId id) {
		this.id = id;
	}

}
