package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryFaultComId generated by hbm2java
 */
public class DmmRepositoryFaultComId extends CompositeIdentifier {

	private String assetId;
	private String faultComponent;

	public DmmRepositoryFaultComId() {
	}

	public DmmRepositoryFaultComId(String assetId, String faultComponent) {
		this.assetId = assetId;
		this.faultComponent = faultComponent;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getFaultComponent() {
		return this.faultComponent;
	}

	public void setFaultComponent(String faultComponent) {
		this.faultComponent = faultComponent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryFaultComId))
			return false;
		DmmRepositoryFaultComId castOther = (DmmRepositoryFaultComId) other;

		return ((this.getAssetId() == castOther.getAssetId()) || (this
				.getAssetId() != null && castOther.getAssetId() != null && this
				.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getFaultComponent() == castOther.getFaultComponent()) || (this
						.getFaultComponent() != null
						&& castOther.getFaultComponent() != null && this
						.getFaultComponent().equals(
								castOther.getFaultComponent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37
				* result
				+ (getFaultComponent() == null ? 0 : this.getFaultComponent()
						.hashCode());
		return result;
	}

}
