package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryFaultDescId generated by hbm2java
 */
public class DmmRepositoryFaultDescId extends CompositeIdentifier {

	private String assetId;
	private String faultDescription;

	public DmmRepositoryFaultDescId() {
	}

	public DmmRepositoryFaultDescId(String assetId, String faultDescription) {
		this.assetId = assetId;
		this.faultDescription = faultDescription;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getFaultDescription() {
		return this.faultDescription;
	}

	public void setFaultDescription(String faultDescription) {
		this.faultDescription = faultDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryFaultDescId))
			return false;
		DmmRepositoryFaultDescId castOther = (DmmRepositoryFaultDescId) other;

		return ((this.getAssetId() == castOther.getAssetId()) || (this
				.getAssetId() != null && castOther.getAssetId() != null && this
				.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getFaultDescription() == castOther
						.getFaultDescription()) || (this.getFaultDescription() != null
						&& castOther.getFaultDescription() != null && this
						.getFaultDescription().equals(
								castOther.getFaultDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37
				* result
				+ (getFaultDescription() == null ? 0 : this
						.getFaultDescription().hashCode());
		return result;
	}

}
