package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryCommId generated by hbm2java
 */
public class DmmRepositoryHistoryCommId extends CompositeIdentifier {

	private String historyId;
	private String faultComponent;

	public DmmRepositoryHistoryCommId() {
	}

	public DmmRepositoryHistoryCommId(String historyId, String faultComponent) {
		this.historyId = historyId;
		this.faultComponent = faultComponent;
	}

	public String getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(String historyId) {
		this.historyId = historyId;
	}

	public String getFaultComponent() {
		return this.faultComponent;
	}

	public void setFaultComponent(String faultComponent) {
		this.faultComponent = faultComponent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryHistoryCommId))
			return false;
		DmmRepositoryHistoryCommId castOther = (DmmRepositoryHistoryCommId) other;

		return ((this.getHistoryId() == castOther.getHistoryId()) || (this
				.getHistoryId() != null && castOther.getHistoryId() != null && this
				.getHistoryId().equals(castOther.getHistoryId())))
				&& ((this.getFaultComponent() == castOther.getFaultComponent()) || (this
						.getFaultComponent() != null
						&& castOther.getFaultComponent() != null && this
						.getFaultComponent().equals(
								castOther.getFaultComponent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHistoryId() == null ? 0 : this.getHistoryId().hashCode());
		result = 37
				* result
				+ (getFaultComponent() == null ? 0 : this.getFaultComponent()
						.hashCode());
		return result;
	}

}
