package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.bean.CompositeIdentifier;

// Generated 2017/1/24 �U�� 02:56:57 by Hibernate Tools 3.4.0.CR1

/**
 * DmmRepositoryHistoryMonthlyComId generated by hbm2java
 */
public class DmmRepositoryHistoryMonthlyComId extends CompositeIdentifier {

	private String monthYear;
	private String assetId;
	private String faultComponent;

	public DmmRepositoryHistoryMonthlyComId() {
	}

	public DmmRepositoryHistoryMonthlyComId(String monthYear, String assetId,
			String faultComponent) {
		this.monthYear = monthYear;
		this.assetId = assetId;
		this.faultComponent = faultComponent;
	}

	public String getMonthYear() {
		return this.monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}


	/**
	 * @return the assetId
	 */
	public String getAssetId() {
		return assetId;
	}

	/**
	 * @param assetId the assetId to set
	 */
	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getFaultComponent() {
		return this.faultComponent;
	}

	public void setFaultComponent(String faultComponent) {
		this.faultComponent = faultComponent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmmRepositoryHistoryMonthlyComId))
			return false;
		DmmRepositoryHistoryMonthlyComId castOther = (DmmRepositoryHistoryMonthlyComId) other;

		return ((this.getMonthYear() == castOther.getMonthYear()) || (this
				.getMonthYear() != null && castOther.getMonthYear() != null && this
				.getMonthYear().equals(castOther.getMonthYear())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null
						&& castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getFaultComponent() == castOther.getFaultComponent()) || (this
						.getFaultComponent() != null
						&& castOther.getFaultComponent() != null && this
						.getFaultComponent().equals(
								castOther.getFaultComponent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMonthYear() == null ? 0 : this.getMonthYear().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37
				* result
				+ (getFaultComponent() == null ? 0 : this.getFaultComponent()
						.hashCode());
		return result;
	}

}
