package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/8/5 �U�� 01:28:31 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.PvmDtidDefDTO;

/**
 * PvmDtidDef generated by hbm2java
 */
public class PvmDtidDef extends DomainModelObject<String, PvmDtidDefDTO> {

	private String id;
	private String companyId;
	private String assetTypeId;
	private String dtidStart;
	private String dtidEnd;
	private String currentNumber;
	private String comment;
	private String createdById;
	private String createdByName;
	private Timestamp createdDate;
	private String updatedById;
	private String updatedByName;
	private Timestamp updatedDate;

	public PvmDtidDef() {
	}

	public PvmDtidDef(String id) {
		this.id = id;
	}

	public PvmDtidDef(String id, String companyId, String assetTypeId,
			String dtidStart, String dtidEnd, String currentNumber,
			String comment, String createdById, String createdByName,
			Timestamp createdDate, String updatedById, String updatedByName,
			Timestamp updatedDate) {
		this.id = id;
		this.companyId = companyId;
		this.assetTypeId = assetTypeId;
		this.dtidStart = dtidStart;
		this.dtidEnd = dtidEnd;
		this.currentNumber = currentNumber;
		this.comment = comment;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the companyId
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * @param companyId the companyId to set
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * @return the assetTypeId
	 */
	public String getAssetTypeId() {
		return assetTypeId;
	}

	/**
	 * @param assetTypeId the assetTypeId to set
	 */
	public void setAssetTypeId(String assetTypeId) {
		this.assetTypeId = assetTypeId;
	}

	/**
	 * @return the dtidStart
	 */
	public String getDtidStart() {
		return dtidStart;
	}

	/**
	 * @param dtidStart the dtidStart to set
	 */
	public void setDtidStart(String dtidStart) {
		this.dtidStart = dtidStart;
	}

	/**
	 * @return the dtidEnd
	 */
	public String getDtidEnd() {
		return dtidEnd;
	}

	/**
	 * @param dtidEnd the dtidEnd to set
	 */
	public void setDtidEnd(String dtidEnd) {
		this.dtidEnd = dtidEnd;
	}

	/**
	 * @return the currentNumber
	 */
	public String getCurrentNumber() {
		return currentNumber;
	}

	/**
	 * @param currentNumber the currentNumber to set
	 */
	public void setCurrentNumber(String currentNumber) {
		this.currentNumber = currentNumber;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the createdById
	 */
	public String getCreatedById() {
		return createdById;
	}

	/**
	 * @param createdById the createdById to set
	 */
	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	/**
	 * @return the createdByName
	 */
	public String getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public Timestamp getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Timestamp getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Timestamp updatedDate) {
		this.updatedDate = updatedDate;
	}

}
