package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2016/12/7 �U�� 02:32:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseDetailDTO;

/**
 * SrmCaseDetail generated by hbm2java
 */
public class SrmCaseDetail extends DomainModelObject<String, SrmCaseDetailDTO>{

	private String caseId;
	private String businessType;
	private String caseType;
	private String processId;
	private String activitiTaskId;
	private String caseStage;
	private String caseTitle;
	private String caseStatus;
	private String caseSubstatus;
	private String caseAction;
	private String caseAssignerId;
	private String caseAssignerName;
	private String caseAcquiredId;
	private Date updateDate;
	private Date caseClosedDate;
	private String createdById;
	private String createdByName;
	private Date createdDate;
	private String updateById;
	private String updateByName;
	private String caseAcquiredName;

	public SrmCaseDetail() {
	}

	public SrmCaseDetail(String caseId, String businessType, String processId) {
		this.caseId = caseId;
		this.businessType = businessType;
		this.processId = processId;
	}

	public SrmCaseDetail(String caseId, String businessType, String caseType,
			String processId, String activitiTaskId, String caseStage,
			String caseTitle, String caseStatus, String caseSubstatus,
			String caseAction, String caseAssignerId, String caseAssignerName,
			String caseAcquiredId, Date updateDate, Date caseClosedDate,
			String createdById, String createdByName, Date createdDate,
			String updateById, String updateByName, String caseAcquiredName) {
		this.caseId = caseId;
		this.businessType = businessType;
		this.caseType = caseType;
		this.processId = processId;
		this.activitiTaskId = activitiTaskId;
		this.caseStage = caseStage;
		this.caseTitle = caseTitle;
		this.caseStatus = caseStatus;
		this.caseSubstatus = caseSubstatus;
		this.caseAction = caseAction;
		this.caseAssignerId = caseAssignerId;
		this.caseAssignerName = caseAssignerName;
		this.caseAcquiredId = caseAcquiredId;
		this.updateDate = updateDate;
		this.caseClosedDate = caseClosedDate;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updateById = updateById;
		this.updateByName = updateByName;
		this.caseAcquiredName = caseAcquiredName;
	}

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getActivitiTaskId() {
		return this.activitiTaskId;
	}

	public void setActivitiTaskId(String activitiTaskId) {
		this.activitiTaskId = activitiTaskId;
	}

	public String getCaseStage() {
		return this.caseStage;
	}

	public void setCaseStage(String caseStage) {
		this.caseStage = caseStage;
	}

	public String getCaseTitle() {
		return this.caseTitle;
	}

	public void setCaseTitle(String caseTitle) {
		this.caseTitle = caseTitle;
	}

	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public String getCaseSubstatus() {
		return this.caseSubstatus;
	}

	public void setCaseSubstatus(String caseSubstatus) {
		this.caseSubstatus = caseSubstatus;
	}

	public String getCaseAction() {
		return this.caseAction;
	}

	public void setCaseAction(String caseAction) {
		this.caseAction = caseAction;
	}

	public String getCaseAssignerId() {
		return this.caseAssignerId;
	}

	public void setCaseAssignerId(String caseAssignerId) {
		this.caseAssignerId = caseAssignerId;
	}

	public String getCaseAssignerName() {
		return this.caseAssignerName;
	}

	public void setCaseAssignerName(String caseAssignerName) {
		this.caseAssignerName = caseAssignerName;
	}

	public String getCaseAcquiredId() {
		return this.caseAcquiredId;
	}

	public void setCaseAcquiredId(String caseAcquiredId) {
		this.caseAcquiredId = caseAcquiredId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCaseClosedDate() {
		return this.caseClosedDate;
	}

	public void setCaseClosedDate(Date caseClosedDate) {
		this.caseClosedDate = caseClosedDate;
	}

	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdateById() {
		return this.updateById;
	}

	public void setUpdateById(String updateById) {
		this.updateById = updateById;
	}

	public String getUpdateByName() {
		return this.updateByName;
	}

	public void setUpdateByName(String updateByName) {
		this.updateByName = updateByName;
	}

	public String getCaseAcquiredName() {
		return this.caseAcquiredName;
	}

	public void setCaseAcquiredName(String caseAcquiredName) {
		this.caseAcquiredName = caseAcquiredName;
	}

}
