package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseTemplatesDTO;

import cafe.core.dmo.DomainModelObject;

/**
 * SrmCaseAttFile generated by hbm2java
 */
public class SrmCaseTemplates extends DomainModelObject<String, SrmCaseTemplatesDTO>{

	private String id;
	private String category;
	private String fileName;
	private String filePath;	
	private String createdById;
	private String createdByName;
	private Date createdDate;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;
	private String deleted;

	public SrmCaseTemplates() {
	}

	public SrmCaseTemplates(String id) {
		this.id = id;
	}

	public SrmCaseTemplates(String id,
			String category, String fileName,
			String filePath, String createdById,
			String createdByName, Date createdDate, String updatedById,
			String updatedByName, Date updatedDate, String deleted) {
		this.id = id;
		this.category = category;
		this.fileName = fileName;
		this.filePath = filePath;
		this.deleted = deleted;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getCreatedById() {
		return createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedById() {
		return updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

}
