package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseTransactionDTO;

/**
 * SrmCaseTransaction generated by hbm2java
 */
public class SrmCaseTransaction extends DomainModelObject<String, SrmCaseTransactionDTO>{

	private String transactionId;
	private String caseId;
	private String actionId;
	private String caseStatus;
	private String deptCode;
	private String dealById;
	private String dealByName;
	private Date dealDate;
	private String description;
	private String caseStage;
	private String caseStageName;
	private String nextCaseStage;
	private String nextCaseStageName;
	private Date delayTime;
	private String checkResult;
	private String problemReason;
	private String problemSolution;
	private String responsibity;
	private String caseType;
	private Date expectedCompletionDate;
	private String createdById;
	private String createdByName;
	private Date createdDate;
	private String problemReasonCode;
	private String problemSolutionCode;
	private String updateItem;
	private String mailInfo;
	private String logisticsVendor;

	public SrmCaseTransaction() {
	}

	public SrmCaseTransaction(String transactionId,
			String caseId, String actionId,
			String caseStatus) {
		this.transactionId = transactionId;
		this.caseId = caseId;
		this.actionId = actionId;
		this.caseStatus = caseStatus;
	}

	public SrmCaseTransaction(String transactionId, String caseId, String actionId, String caseStatus, String deptCode,
			String dealById, String dealByName, Date dealDate, String description, String caseStage,
			String caseStageName, String nextCaseStage, String nextCaseStageName, Date delayTime, String checkResult,
			String problemReason, String problemSolution, String responsibity, String caseType,
			Date expectedCompletionDate, String createdById, String createdByName, Date createdDate,
			String problemReasonCode, String problemSolutionCode, String updateItem, String mailInfo, String logisticsVendor) {
		this.transactionId = transactionId;
		this.caseId = caseId;
		this.actionId = actionId;
		this.caseStatus = caseStatus;
		this.deptCode = deptCode;
		this.dealById = dealById;
		this.dealByName = dealByName;
		this.dealDate = dealDate;
		this.description = description;
		this.caseStage = caseStage;
		this.caseStageName = caseStageName;
		this.nextCaseStage = nextCaseStage;
		this.nextCaseStageName = nextCaseStageName;
		this.delayTime = delayTime;
		this.checkResult = checkResult;
		this.problemReason = problemReason;
		this.problemSolution = problemSolution;
		this.responsibity = responsibity;
		this.caseType = caseType;
		this.expectedCompletionDate = expectedCompletionDate;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.problemReasonCode = problemReasonCode;
		this.problemSolutionCode = problemSolutionCode;
		this.updateItem = updateItem;
		this.mailInfo = mailInfo;
		this.logisticsVendor = logisticsVendor;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getCaseId() {
		return caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDealById() {
		return this.dealById;
	}

	public void setDealById(String dealById) {
		this.dealById = dealById;
	}

	public String getDealByName() {
		return this.dealByName;
	}

	public void setDealByName(String dealByName) {
		this.dealByName = dealByName;
	}

	public Date getDealDate() {
		return this.dealDate;
	}

	public void setDealDate(Date dealDate) {
		this.dealDate = dealDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCaseStage() {
		return this.caseStage;
	}

	public void setCaseStage(String caseStage) {
		this.caseStage = caseStage;
	}

	public String getCaseStageName() {
		return this.caseStageName;
	}

	public void setCaseStageName(String caseStageName) {
		this.caseStageName = caseStageName;
	}

	public String getNextCaseStage() {
		return this.nextCaseStage;
	}

	public void setNextCaseStage(String nextCaseStage) {
		this.nextCaseStage = nextCaseStage;
	}

	public String getNextCaseStageName() {
		return this.nextCaseStageName;
	}

	public void setNextCaseStageName(String nextCaseStageName) {
		this.nextCaseStageName = nextCaseStageName;
	}

	public Date getDelayTime() {
		return this.delayTime;
	}

	public void setDelayTime(Date delayTime) {
		this.delayTime = delayTime;
	}

	public String getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	public String getProblemReason() {
		return this.problemReason;
	}

	public void setProblemReason(String problemReason) {
		this.problemReason = problemReason;
	}

	public String getProblemSolution() {
		return this.problemSolution;
	}

	public void setProblemSolution(String problemSolution) {
		this.problemSolution = problemSolution;
	}

	public String getResponsibity() {
		return this.responsibity;
	}

	public void setResponsibity(String responsibity) {
		this.responsibity = responsibity;
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	public Date getExpectedCompletionDate() {
		return this.expectedCompletionDate;
	}

	public void setExpectedCompletionDate(Date expectedCompletionDate) {
		this.expectedCompletionDate = expectedCompletionDate;
	}

	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the problemReasonCode
	 */
	public String getProblemReasonCode() {
		return problemReasonCode;
	}

	/**
	 * @param problemReasonCode the problemReasonCode to set
	 */
	public void setProblemReasonCode(String problemReasonCode) {
		this.problemReasonCode = problemReasonCode;
	}

	/**
	 * @return the problemSolutionCode
	 */
	public String getProblemSolutionCode() {
		return problemSolutionCode;
	}

	/**
	 * @param problemSolutionCode the problemSolutionCode to set
	 */
	public void setProblemSolutionCode(String problemSolutionCode) {
		this.problemSolutionCode = problemSolutionCode;
	}

	/**
	 * @return the updateItem
	 */
	public String getUpdateItem() {
		return updateItem;
	}

	/**
	 * @param updateItem the updateItem to set
	 */
	public void setUpdateItem(String updateItem) {
		this.updateItem = updateItem;
	}

	/**
	 * @return the mailInfo
	 */
	public String getMailInfo() {
		return mailInfo;
	}

	/**
	 * @param mailInfo the mailInfo to set
	 */
	public void setMailInfo(String mailInfo) {
		this.mailInfo = mailInfo;
	}

	/**
	 * @return the logisticsVendor
	 */
	public String getLogisticsVendor() {
		return logisticsVendor;
	}

	/**
	 * @param logisticsVendor the logisticsVendor to set
	 */
	public void setLogisticsVendor(String logisticsVendor) {
		this.logisticsVendor = logisticsVendor;
	}
	
}
