package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseAssetFunctionDTO;
import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseCommModeDTO;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

/**
 * SrmCaseAssetFunction generated by hbm2java
 */
public class SrmCaseNewCommMode extends DomainModelObject<String, SrmCaseCommModeDTO>{

	private String id;
	private String caseId;
	private String commModeId;
	
	public SrmCaseNewCommMode() {
	}

	public SrmCaseNewCommMode(String id) {
		this.id = id;
	}

	public SrmCaseNewCommMode(String id, String caseId, String commModeId) {
		this.id = id;
		this.caseId = caseId;
		this.commModeId = commModeId;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the caseId
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the commModeId
	 */
	public String getCommModeId() {
		return commModeId;
	}

	/**
	 * @param commModeId the commModeId to set
	 */
	public void setCommModeId(String commModeId) {
		this.commModeId = commModeId;
	}

}
