package com.cybersoft4u.xian.iatoms.services.dmo;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseAssetFunctionDTO;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

/**
 * SrmCaseNewAssetFunction generated by hbm2java
 */
public class SrmCaseNewAssetFunction extends DomainModelObject<String, SrmCaseAssetFunctionDTO>{

	private String id;
	private String caseId;
	private String functionCategory;
	private String functionId;

	public SrmCaseNewAssetFunction() {
	}

	public SrmCaseNewAssetFunction(String id) {
		this.id = id;
	}

	public SrmCaseNewAssetFunction(String id,
			String caseId, String functionCategory,
			String functionId) {
		this.id = id;
		this.caseId = caseId;
		this.functionCategory = functionCategory;
		this.functionId = functionId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCaseId() {
		return caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getFunctionCategory() {
		return this.functionCategory;
	}

	public void setFunctionCategory(String functionCategory) {
		this.functionCategory = functionCategory;
	}

	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

}
