package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseHandleInfoDTO;

/**
 * SrmHistoryCaseHandleInfo generated by hbm2java
 */
public class SrmHistoryCaseHandleInfo extends DomainModelObject<String, SrmCaseHandleInfoDTO>{

	private String caseId;
	private String caseCategory;
	private String customerId;
	private String contractId;
	private String requirementNo;
	private String processType;
	private String installType;
	private String dtid;
	private String companyId;
	private String departmentId;
	private String isProject = "N";
	private String projectCode;
	private String projectName;
	private String caseType;
	private Date expectedCompletionDate;
	private String merchantCode;
	private String oldMerchantCode;
	private String merchantHeaderId;
	private String installedAdress;
	private String installedAdressLocation;
	private String installedContact;
	private String installedContactPhone;
	private String edcType;
	private String softwareVersion;
	private String builtInFeature;
	private String multiModule;
	private String peripherals;
	private String peripheralsFunction;
	private String ecrConnection;
	private String peripherals2;
	private String peripheralsFunction2;
	private String connectionType;
	private String peripherals3;
	private String peripheralsFunction3;
	private String localhostIp;
	private String netVendorId;
	private String gateway;
	private String netmask;
	private String description;
	private Integer attendanceTimes;
	private Integer repairTimes;
	private String repairReason;
	private String uninstallType;
	private String createdById;
	private String createdByName;
	private Date createdDate;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;
	private Date createdFinishDate;
	private Date acceptableResponseDate;
	private Date acceptableArriveDate;
	private Date acceptableFinishDate;
	private Date closeDate;
	private String caseStatus;
	private String dispatchDeptId;
	private String updatedDescription;
	private String contactAddressLocation;
	private String contactAddress;
	private String contactUser;
	private String contactUserPhone;
	private String dispatchProcessUser;
	private String dispatchProcessUsername;
	private String dispatchUser;
	private String dispatchUserName;
	private Date dispatchDate;
	private String responseUser;
	private String responseUserName;
	private Date responseDate;
	private String arriveUser;
	private String arriveUserName;
	private Date arriveDate;
	private String completeUser;
	private String completeUserName;
	private Date completeDate;
	private String analyzeUser;
	private String analyzeUserName;
	private Date analyzeDate;
	private String closeUser;
	private String closeUserName;
	private String installedDeptId;
	private String installedUser;
	private String isTms = "N";
	private String problemReason;
	private String problemSolution;
	private String responsibity;
	private String isBussinessAddress = "E";
	private String isBussinessContact = "E";
	private String isBussinessContactPhone = "E";
	private String contactIsBussinessAddress = "E";
	private String contactIsBussinessContact = "E";
	private String contactIsBussinessContactPhone = "E";
	private Double responseWarnning;
	private Double arriveWarnning;
	private Double completeWarnning;
	private Date installedDate;
	private Date uninstalledDate;
	private Date cupEnableDate;
	private Date cupDisableDate;
	private String updateItem;
	private String problemReasonCode;
	private String problemSolutionCode;
	private String electronicInvoice;
	private String cupQuickPass;
	private String sameInstalled;
	private String tmsParamDesc;
	private String fomsCase = "N";
	private String isFirstInstalled = "N";
	private String logoStyle;
	private String isOpenEncrypt;
	private String electronicPayPlatform;
	private String completeDepartmentId;
	private String hasOnlineExclusion = "N";
	private String firstDescription;
	private String secondDescription;
	private String thirdDescription;
	private String hasRetreat = "N";
	private String hasDelay = "N";
	private String isBussinessContactMobilePhone = "N";
	private String isBussinessContactEmail = "N";
	private String installedContactMobilePhone;
	private String installedContactEmail;
	private String contactIsBussinessContactMobilePhone = "N";
	private String contactIsBussinessContactEmail = "N";
	private String contactMobilePhone;
	private String contactUserEmail;
	private String cmsCase;
	private String installCaseId;
	private Date installCompleteDate;
	private String installedPostCode;
	private String contactPostCode;
	private String logisticsVendor;
	private String logisticsNumber;
	private String receiptType;

	public SrmHistoryCaseHandleInfo() {
	}

	public SrmHistoryCaseHandleInfo(String caseId, String caseCategory) {
		this.caseId = caseId;
		this.caseCategory = caseCategory;
	}

	public SrmHistoryCaseHandleInfo(String caseId, String caseCategory,
			String customerId, String contractId, String requirementNo,
			String processType, String installType, String dtid,
			String companyId, String departmentId, String isProject,
			String projectCode, String projectName, String caseType,
			Date expectedCompletionDate, String merchantCode,
			String oldMerchantCode, String merchantHeaderId,
			String installedAdress, String installedAdressLocation,
			String installedContact, String installedContactPhone,
			String edcType, String softwareVersion, String builtInFeature,
			String multiModule, String peripherals, String peripheralsFunction,
			String ecrConnection, String peripherals2,
			String peripheralsFunction2, String connectionType,
			String peripherals3, String peripheralsFunction3,
			String localhostIp, String netVendorId, String gateway,
			String netmask, String description, Integer attendanceTimes,
			Integer repairTimes, String repairReason, String uninstallType,
			String createdById, String createdByName, Date createdDate,
			String updatedById, String updatedByName, Date updatedDate,
			Date createdFinishDate, Date acceptableResponseDate,
			Date acceptableArriveDate, Date acceptableFinishDate,
			Date closeDate, String caseStatus, String dispatchDeptId,
			String updatedDescription, String contactAddressLocation,
			String contactAddress, String contactUser, String contactUserPhone,
			String dispatchProcessUser, String dispatchProcessUsername,
			String dispatchUser, String dispatchUserName, Date dispatchDate,
			String responseUser, String responseUserName, Date responseDate,
			String arriveUser, String arriveUserName, Date arriveDate,
			String completeUser, String completeUserName, Date completeDate,
			String analyzeUser, String analyzeUserName, Date analyzeDate,
			String closeUser, String closeUserName, String installedDeptId,
			String installedUser, String isTms, String problemReason,
			String problemSolution, String responsibity,
			String isBussinessAddress, String isBussinessContact,
			String isBussinessContactPhone, String contactIsBussinessAddress,
			String contactIsBussinessContact,
			String contactIsBussinessContactPhone, Double responseWarnning,
			Double arriveWarnning, Double completeWarnning, Date installedDate,
			Date uninstalledDate, Date cupEnableDate, Date cupDisableDate,
			String updateItem, String problemReasonCode,
			String problemSolutionCode, String electronicInvoice,
			String cupQuickPass, String sameInstalled, String tmsParamDesc,
			String fomsCase, String isFirstInstalled, String logoStyle,
			String isOpenEncrypt, String electronicPayPlatform,
			String completeDepartmentId, String hasOnlineExclusion,
			String firstDescription, String secondDescription,
			String thirdDescription, String hasRetreat, String hasDelay,
			String isBussinessContactMobilePhone,
			String isBussinessContactEmail, String installedContactMobilePhone,
			String installedContactEmail,
			String contactIsBussinessContactMobilePhone,
			String contactIsBussinessContactEmail, String contactMobilePhone,
			String contactUserEmail, String cmsCase, String installCaseId,
			Date installCompleteDate, String installedPostCode, String contactPostCode, String logisticsVendor,
			String logisticsNumber, String receiptType) {
		super();
		this.caseId = caseId;
		this.caseCategory = caseCategory;
		this.customerId = customerId;
		this.contractId = contractId;
		this.requirementNo = requirementNo;
		this.processType = processType;
		this.installType = installType;
		this.dtid = dtid;
		this.companyId = companyId;
		this.departmentId = departmentId;
		this.isProject = isProject;
		this.projectCode = projectCode;
		this.projectName = projectName;
		this.caseType = caseType;
		this.expectedCompletionDate = expectedCompletionDate;
		this.merchantCode = merchantCode;
		this.oldMerchantCode = oldMerchantCode;
		this.merchantHeaderId = merchantHeaderId;
		this.installedAdress = installedAdress;
		this.installedAdressLocation = installedAdressLocation;
		this.installedContact = installedContact;
		this.installedContactPhone = installedContactPhone;
		this.edcType = edcType;
		this.softwareVersion = softwareVersion;
		this.builtInFeature = builtInFeature;
		this.multiModule = multiModule;
		this.peripherals = peripherals;
		this.peripheralsFunction = peripheralsFunction;
		this.ecrConnection = ecrConnection;
		this.peripherals2 = peripherals2;
		this.peripheralsFunction2 = peripheralsFunction2;
		this.connectionType = connectionType;
		this.peripherals3 = peripherals3;
		this.peripheralsFunction3 = peripheralsFunction3;
		this.localhostIp = localhostIp;
		this.netVendorId = netVendorId;
		this.gateway = gateway;
		this.netmask = netmask;
		this.description = description;
		this.attendanceTimes = attendanceTimes;
		this.repairTimes = repairTimes;
		this.repairReason = repairReason;
		this.uninstallType = uninstallType;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.createdFinishDate = createdFinishDate;
		this.acceptableResponseDate = acceptableResponseDate;
		this.acceptableArriveDate = acceptableArriveDate;
		this.acceptableFinishDate = acceptableFinishDate;
		this.closeDate = closeDate;
		this.caseStatus = caseStatus;
		this.dispatchDeptId = dispatchDeptId;
		this.updatedDescription = updatedDescription;
		this.contactAddressLocation = contactAddressLocation;
		this.contactAddress = contactAddress;
		this.contactUser = contactUser;
		this.contactUserPhone = contactUserPhone;
		this.dispatchProcessUser = dispatchProcessUser;
		this.dispatchProcessUsername = dispatchProcessUsername;
		this.dispatchUser = dispatchUser;
		this.dispatchUserName = dispatchUserName;
		this.dispatchDate = dispatchDate;
		this.responseUser = responseUser;
		this.responseUserName = responseUserName;
		this.responseDate = responseDate;
		this.arriveUser = arriveUser;
		this.arriveUserName = arriveUserName;
		this.arriveDate = arriveDate;
		this.completeUser = completeUser;
		this.completeUserName = completeUserName;
		this.completeDate = completeDate;
		this.analyzeUser = analyzeUser;
		this.analyzeUserName = analyzeUserName;
		this.analyzeDate = analyzeDate;
		this.closeUser = closeUser;
		this.closeUserName = closeUserName;
		this.installedDeptId = installedDeptId;
		this.installedUser = installedUser;
		this.isTms = isTms;
		this.problemReason = problemReason;
		this.problemSolution = problemSolution;
		this.responsibity = responsibity;
		this.isBussinessAddress = isBussinessAddress;
		this.isBussinessContact = isBussinessContact;
		this.isBussinessContactPhone = isBussinessContactPhone;
		this.contactIsBussinessAddress = contactIsBussinessAddress;
		this.contactIsBussinessContact = contactIsBussinessContact;
		this.contactIsBussinessContactPhone = contactIsBussinessContactPhone;
		this.responseWarnning = responseWarnning;
		this.arriveWarnning = arriveWarnning;
		this.completeWarnning = completeWarnning;
		this.installedDate = installedDate;
		this.uninstalledDate = uninstalledDate;
		this.cupEnableDate = cupEnableDate;
		this.cupDisableDate = cupDisableDate;
		this.updateItem = updateItem;
		this.problemReasonCode = problemReasonCode;
		this.problemSolutionCode = problemSolutionCode;
		this.electronicInvoice = electronicInvoice;
		this.cupQuickPass = cupQuickPass;
		this.sameInstalled = sameInstalled;
		this.tmsParamDesc = tmsParamDesc;
		this.fomsCase = fomsCase;
		this.isFirstInstalled = isFirstInstalled;
		this.logoStyle = logoStyle;
		this.isOpenEncrypt = isOpenEncrypt;
		this.electronicPayPlatform = electronicPayPlatform;
		this.completeDepartmentId = completeDepartmentId;
		this.hasOnlineExclusion = hasOnlineExclusion;
		this.firstDescription = firstDescription;
		this.secondDescription = secondDescription;
		this.thirdDescription = thirdDescription;
		this.hasRetreat = hasRetreat;
		this.hasDelay = hasDelay;
		this.isBussinessContactMobilePhone = isBussinessContactMobilePhone;
		this.isBussinessContactEmail = isBussinessContactEmail;
		this.installedContactMobilePhone = installedContactMobilePhone;
		this.installedContactEmail = installedContactEmail;
		this.contactIsBussinessContactMobilePhone = contactIsBussinessContactMobilePhone;
		this.contactIsBussinessContactEmail = contactIsBussinessContactEmail;
		this.contactMobilePhone = contactMobilePhone;
		this.contactUserEmail = contactUserEmail;
		this.cmsCase = cmsCase;
		this.installCaseId = installCaseId;
		this.installCompleteDate = installCompleteDate;
		this.installedPostCode = installedPostCode;
		this.contactPostCode = contactPostCode;
		this.logisticsVendor = logisticsVendor;
		this.logisticsNumber = logisticsNumber;
		this.receiptType = receiptType;
	}

	/**
	 * @return the caseId
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the caseCategory
	 */
	public String getCaseCategory() {
		return caseCategory;
	}

	/**
	 * @param caseCategory the caseCategory to set
	 */
	public void setCaseCategory(String caseCategory) {
		this.caseCategory = caseCategory;
	}

	/**
	 * @return the customerId
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * @param customerId the customerId to set
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	/**
	 * @return the contractId
	 */
	public String getContractId() {
		return contractId;
	}

	/**
	 * @param contractId the contractId to set
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	/**
	 * @return the requirementNo
	 */
	public String getRequirementNo() {
		return requirementNo;
	}

	/**
	 * @param requirementNo the requirementNo to set
	 */
	public void setRequirementNo(String requirementNo) {
		this.requirementNo = requirementNo;
	}

	/**
	 * @return the processType
	 */
	public String getProcessType() {
		return processType;
	}

	/**
	 * @param processType the processType to set
	 */
	public void setProcessType(String processType) {
		this.processType = processType;
	}

	/**
	 * @return the installType
	 */
	public String getInstallType() {
		return installType;
	}

	/**
	 * @param installType the installType to set
	 */
	public void setInstallType(String installType) {
		this.installType = installType;
	}

	/**
	 * @return the dtid
	 */
	public String getDtid() {
		return dtid;
	}

	/**
	 * @param dtid the dtid to set
	 */
	public void setDtid(String dtid) {
		this.dtid = dtid;
	}

	/**
	 * @return the companyId
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * @param companyId the companyId to set
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * @return the departmentId
	 */
	public String getDepartmentId() {
		return departmentId;
	}

	/**
	 * @param departmentId the departmentId to set
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * @return the isProject
	 */
	public String getIsProject() {
		return isProject;
	}

	/**
	 * @param isProject the isProject to set
	 */
	public void setIsProject(String isProject) {
		this.isProject = isProject;
	}

	/**
	 * @return the projectCode
	 */
	public String getProjectCode() {
		return projectCode;
	}

	/**
	 * @param projectCode the projectCode to set
	 */
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	/**
	 * @return the projectName
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * @param projectName the projectName to set
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * @return the caseType
	 */
	public String getCaseType() {
		return caseType;
	}

	/**
	 * @param caseType the caseType to set
	 */
	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	/**
	 * @return the expectedCompletionDate
	 */
	public Date getExpectedCompletionDate() {
		return expectedCompletionDate;
	}

	/**
	 * @param expectedCompletionDate the expectedCompletionDate to set
	 */
	public void setExpectedCompletionDate(Date expectedCompletionDate) {
		this.expectedCompletionDate = expectedCompletionDate;
	}

	/**
	 * @return the merchantCode
	 */
	public String getMerchantCode() {
		return merchantCode;
	}

	/**
	 * @param merchantCode the merchantCode to set
	 */
	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	/**
	 * @return the oldMerchantCode
	 */
	public String getOldMerchantCode() {
		return oldMerchantCode;
	}

	/**
	 * @param oldMerchantCode the oldMerchantCode to set
	 */
	public void setOldMerchantCode(String oldMerchantCode) {
		this.oldMerchantCode = oldMerchantCode;
	}

	/**
	 * @return the merchantHeaderId
	 */
	public String getMerchantHeaderId() {
		return merchantHeaderId;
	}

	/**
	 * @param merchantHeaderId the merchantHeaderId to set
	 */
	public void setMerchantHeaderId(String merchantHeaderId) {
		this.merchantHeaderId = merchantHeaderId;
	}

	/**
	 * @return the installedAdress
	 */
	public String getInstalledAdress() {
		return installedAdress;
	}

	/**
	 * @param installedAdress the installedAdress to set
	 */
	public void setInstalledAdress(String installedAdress) {
		this.installedAdress = installedAdress;
	}

	/**
	 * @return the installedAdressLocation
	 */
	public String getInstalledAdressLocation() {
		return installedAdressLocation;
	}

	/**
	 * @param installedAdressLocation the installedAdressLocation to set
	 */
	public void setInstalledAdressLocation(String installedAdressLocation) {
		this.installedAdressLocation = installedAdressLocation;
	}

	/**
	 * @return the installedContact
	 */
	public String getInstalledContact() {
		return installedContact;
	}

	/**
	 * @param installedContact the installedContact to set
	 */
	public void setInstalledContact(String installedContact) {
		this.installedContact = installedContact;
	}

	/**
	 * @return the installedContactPhone
	 */
	public String getInstalledContactPhone() {
		return installedContactPhone;
	}

	/**
	 * @param installedContactPhone the installedContactPhone to set
	 */
	public void setInstalledContactPhone(String installedContactPhone) {
		this.installedContactPhone = installedContactPhone;
	}

	/**
	 * @return the edcType
	 */
	public String getEdcType() {
		return edcType;
	}

	/**
	 * @param edcType the edcType to set
	 */
	public void setEdcType(String edcType) {
		this.edcType = edcType;
	}

	/**
	 * @return the softwareVersion
	 */
	public String getSoftwareVersion() {
		return softwareVersion;
	}

	/**
	 * @param softwareVersion the softwareVersion to set
	 */
	public void setSoftwareVersion(String softwareVersion) {
		this.softwareVersion = softwareVersion;
	}

	/**
	 * @return the builtInFeature
	 */
	public String getBuiltInFeature() {
		return builtInFeature;
	}

	/**
	 * @param builtInFeature the builtInFeature to set
	 */
	public void setBuiltInFeature(String builtInFeature) {
		this.builtInFeature = builtInFeature;
	}

	/**
	 * @return the multiModule
	 */
	public String getMultiModule() {
		return multiModule;
	}

	/**
	 * @param multiModule the multiModule to set
	 */
	public void setMultiModule(String multiModule) {
		this.multiModule = multiModule;
	}

	/**
	 * @return the peripherals
	 */
	public String getPeripherals() {
		return peripherals;
	}

	/**
	 * @param peripherals the peripherals to set
	 */
	public void setPeripherals(String peripherals) {
		this.peripherals = peripherals;
	}

	/**
	 * @return the peripheralsFunction
	 */
	public String getPeripheralsFunction() {
		return peripheralsFunction;
	}

	/**
	 * @param peripheralsFunction the peripheralsFunction to set
	 */
	public void setPeripheralsFunction(String peripheralsFunction) {
		this.peripheralsFunction = peripheralsFunction;
	}

	/**
	 * @return the ecrConnection
	 */
	public String getEcrConnection() {
		return ecrConnection;
	}

	/**
	 * @param ecrConnection the ecrConnection to set
	 */
	public void setEcrConnection(String ecrConnection) {
		this.ecrConnection = ecrConnection;
	}

	/**
	 * @return the peripherals2
	 */
	public String getPeripherals2() {
		return peripherals2;
	}

	/**
	 * @param peripherals2 the peripherals2 to set
	 */
	public void setPeripherals2(String peripherals2) {
		this.peripherals2 = peripherals2;
	}

	/**
	 * @return the peripheralsFunction2
	 */
	public String getPeripheralsFunction2() {
		return peripheralsFunction2;
	}

	/**
	 * @param peripheralsFunction2 the peripheralsFunction2 to set
	 */
	public void setPeripheralsFunction2(String peripheralsFunction2) {
		this.peripheralsFunction2 = peripheralsFunction2;
	}

	/**
	 * @return the connectionType
	 */
	public String getConnectionType() {
		return connectionType;
	}

	/**
	 * @param connectionType the connectionType to set
	 */
	public void setConnectionType(String connectionType) {
		this.connectionType = connectionType;
	}

	/**
	 * @return the peripherals3
	 */
	public String getPeripherals3() {
		return peripherals3;
	}

	/**
	 * @param peripherals3 the peripherals3 to set
	 */
	public void setPeripherals3(String peripherals3) {
		this.peripherals3 = peripherals3;
	}

	/**
	 * @return the peripheralsFunction3
	 */
	public String getPeripheralsFunction3() {
		return peripheralsFunction3;
	}

	/**
	 * @param peripheralsFunction3 the peripheralsFunction3 to set
	 */
	public void setPeripheralsFunction3(String peripheralsFunction3) {
		this.peripheralsFunction3 = peripheralsFunction3;
	}

	/**
	 * @return the localhostIp
	 */
	public String getLocalhostIp() {
		return localhostIp;
	}

	/**
	 * @param localhostIp the localhostIp to set
	 */
	public void setLocalhostIp(String localhostIp) {
		this.localhostIp = localhostIp;
	}

	/**
	 * @return the netVendorId
	 */
	public String getNetVendorId() {
		return netVendorId;
	}

	/**
	 * @param netVendorId the netVendorId to set
	 */
	public void setNetVendorId(String netVendorId) {
		this.netVendorId = netVendorId;
	}

	/**
	 * @return the gateway
	 */
	public String getGateway() {
		return gateway;
	}

	/**
	 * @param gateway the gateway to set
	 */
	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	/**
	 * @return the netmask
	 */
	public String getNetmask() {
		return netmask;
	}

	/**
	 * @param netmask the netmask to set
	 */
	public void setNetmask(String netmask) {
		this.netmask = netmask;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the attendanceTimes
	 */
	public Integer getAttendanceTimes() {
		return attendanceTimes;
	}

	/**
	 * @param attendanceTimes the attendanceTimes to set
	 */
	public void setAttendanceTimes(Integer attendanceTimes) {
		this.attendanceTimes = attendanceTimes;
	}

	/**
	 * @return the repairTimes
	 */
	public Integer getRepairTimes() {
		return repairTimes;
	}

	/**
	 * @param repairTimes the repairTimes to set
	 */
	public void setRepairTimes(Integer repairTimes) {
		this.repairTimes = repairTimes;
	}

	/**
	 * @return the repairReason
	 */
	public String getRepairReason() {
		return repairReason;
	}

	/**
	 * @param repairReason the repairReason to set
	 */
	public void setRepairReason(String repairReason) {
		this.repairReason = repairReason;
	}

	/**
	 * @return the uninstallType
	 */
	public String getUninstallType() {
		return uninstallType;
	}

	/**
	 * @param uninstallType the uninstallType to set
	 */
	public void setUninstallType(String uninstallType) {
		this.uninstallType = uninstallType;
	}

	/**
	 * @return the createdById
	 */
	public String getCreatedById() {
		return createdById;
	}

	/**
	 * @param createdById the createdById to set
	 */
	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	/**
	 * @return the createdByName
	 */
	public String getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the createdFinishDate
	 */
	public Date getCreatedFinishDate() {
		return createdFinishDate;
	}

	/**
	 * @param createdFinishDate the createdFinishDate to set
	 */
	public void setCreatedFinishDate(Date createdFinishDate) {
		this.createdFinishDate = createdFinishDate;
	}

	/**
	 * @return the acceptableResponseDate
	 */
	public Date getAcceptableResponseDate() {
		return acceptableResponseDate;
	}

	/**
	 * @param acceptableResponseDate the acceptableResponseDate to set
	 */
	public void setAcceptableResponseDate(Date acceptableResponseDate) {
		this.acceptableResponseDate = acceptableResponseDate;
	}

	/**
	 * @return the acceptableArriveDate
	 */
	public Date getAcceptableArriveDate() {
		return acceptableArriveDate;
	}

	/**
	 * @param acceptableArriveDate the acceptableArriveDate to set
	 */
	public void setAcceptableArriveDate(Date acceptableArriveDate) {
		this.acceptableArriveDate = acceptableArriveDate;
	}

	/**
	 * @return the acceptableFinishDate
	 */
	public Date getAcceptableFinishDate() {
		return acceptableFinishDate;
	}

	/**
	 * @param acceptableFinishDate the acceptableFinishDate to set
	 */
	public void setAcceptableFinishDate(Date acceptableFinishDate) {
		this.acceptableFinishDate = acceptableFinishDate;
	}

	/**
	 * @return the closeDate
	 */
	public Date getCloseDate() {
		return closeDate;
	}

	/**
	 * @param closeDate the closeDate to set
	 */
	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	/**
	 * @return the caseStatus
	 */
	public String getCaseStatus() {
		return caseStatus;
	}

	/**
	 * @param caseStatus the caseStatus to set
	 */
	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	/**
	 * @return the dispatchDeptId
	 */
	public String getDispatchDeptId() {
		return dispatchDeptId;
	}

	/**
	 * @param dispatchDeptId the dispatchDeptId to set
	 */
	public void setDispatchDeptId(String dispatchDeptId) {
		this.dispatchDeptId = dispatchDeptId;
	}

	/**
	 * @return the updatedDescription
	 */
	public String getUpdatedDescription() {
		return updatedDescription;
	}

	/**
	 * @param updatedDescription the updatedDescription to set
	 */
	public void setUpdatedDescription(String updatedDescription) {
		this.updatedDescription = updatedDescription;
	}

	/**
	 * @return the contactAddressLocation
	 */
	public String getContactAddressLocation() {
		return contactAddressLocation;
	}

	/**
	 * @param contactAddressLocation the contactAddressLocation to set
	 */
	public void setContactAddressLocation(String contactAddressLocation) {
		this.contactAddressLocation = contactAddressLocation;
	}

	/**
	 * @return the contactAddress
	 */
	public String getContactAddress() {
		return contactAddress;
	}

	/**
	 * @param contactAddress the contactAddress to set
	 */
	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	/**
	 * @return the contactUser
	 */
	public String getContactUser() {
		return contactUser;
	}

	/**
	 * @param contactUser the contactUser to set
	 */
	public void setContactUser(String contactUser) {
		this.contactUser = contactUser;
	}

	/**
	 * @return the contactUserPhone
	 */
	public String getContactUserPhone() {
		return contactUserPhone;
	}

	/**
	 * @param contactUserPhone the contactUserPhone to set
	 */
	public void setContactUserPhone(String contactUserPhone) {
		this.contactUserPhone = contactUserPhone;
	}

	/**
	 * @return the dispatchProcessUser
	 */
	public String getDispatchProcessUser() {
		return dispatchProcessUser;
	}

	/**
	 * @param dispatchProcessUser the dispatchProcessUser to set
	 */
	public void setDispatchProcessUser(String dispatchProcessUser) {
		this.dispatchProcessUser = dispatchProcessUser;
	}

	/**
	 * @return the dispatchProcessUsername
	 */
	public String getDispatchProcessUsername() {
		return dispatchProcessUsername;
	}

	/**
	 * @param dispatchProcessUsername the dispatchProcessUsername to set
	 */
	public void setDispatchProcessUsername(String dispatchProcessUsername) {
		this.dispatchProcessUsername = dispatchProcessUsername;
	}

	/**
	 * @return the dispatchUser
	 */
	public String getDispatchUser() {
		return dispatchUser;
	}

	/**
	 * @param dispatchUser the dispatchUser to set
	 */
	public void setDispatchUser(String dispatchUser) {
		this.dispatchUser = dispatchUser;
	}

	/**
	 * @return the dispatchUserName
	 */
	public String getDispatchUserName() {
		return dispatchUserName;
	}

	/**
	 * @param dispatchUserName the dispatchUserName to set
	 */
	public void setDispatchUserName(String dispatchUserName) {
		this.dispatchUserName = dispatchUserName;
	}

	/**
	 * @return the dispatchDate
	 */
	public Date getDispatchDate() {
		return dispatchDate;
	}

	/**
	 * @param dispatchDate the dispatchDate to set
	 */
	public void setDispatchDate(Date dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	/**
	 * @return the responseUser
	 */
	public String getResponseUser() {
		return responseUser;
	}

	/**
	 * @param responseUser the responseUser to set
	 */
	public void setResponseUser(String responseUser) {
		this.responseUser = responseUser;
	}

	/**
	 * @return the responseUserName
	 */
	public String getResponseUserName() {
		return responseUserName;
	}

	/**
	 * @param responseUserName the responseUserName to set
	 */
	public void setResponseUserName(String responseUserName) {
		this.responseUserName = responseUserName;
	}

	/**
	 * @return the responseDate
	 */
	public Date getResponseDate() {
		return responseDate;
	}

	/**
	 * @param responseDate the responseDate to set
	 */
	public void setResponseDate(Date responseDate) {
		this.responseDate = responseDate;
	}

	/**
	 * @return the arriveUser
	 */
	public String getArriveUser() {
		return arriveUser;
	}

	/**
	 * @param arriveUser the arriveUser to set
	 */
	public void setArriveUser(String arriveUser) {
		this.arriveUser = arriveUser;
	}

	/**
	 * @return the arriveUserName
	 */
	public String getArriveUserName() {
		return arriveUserName;
	}

	/**
	 * @param arriveUserName the arriveUserName to set
	 */
	public void setArriveUserName(String arriveUserName) {
		this.arriveUserName = arriveUserName;
	}

	/**
	 * @return the arriveDate
	 */
	public Date getArriveDate() {
		return arriveDate;
	}

	/**
	 * @param arriveDate the arriveDate to set
	 */
	public void setArriveDate(Date arriveDate) {
		this.arriveDate = arriveDate;
	}

	/**
	 * @return the completeUser
	 */
	public String getCompleteUser() {
		return completeUser;
	}

	/**
	 * @param completeUser the completeUser to set
	 */
	public void setCompleteUser(String completeUser) {
		this.completeUser = completeUser;
	}

	/**
	 * @return the completeUserName
	 */
	public String getCompleteUserName() {
		return completeUserName;
	}

	/**
	 * @param completeUserName the completeUserName to set
	 */
	public void setCompleteUserName(String completeUserName) {
		this.completeUserName = completeUserName;
	}

	/**
	 * @return the completeDate
	 */
	public Date getCompleteDate() {
		return completeDate;
	}

	/**
	 * @param completeDate the completeDate to set
	 */
	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	/**
	 * @return the analyzeUser
	 */
	public String getAnalyzeUser() {
		return analyzeUser;
	}

	/**
	 * @param analyzeUser the analyzeUser to set
	 */
	public void setAnalyzeUser(String analyzeUser) {
		this.analyzeUser = analyzeUser;
	}

	/**
	 * @return the analyzeUserName
	 */
	public String getAnalyzeUserName() {
		return analyzeUserName;
	}

	/**
	 * @param analyzeUserName the analyzeUserName to set
	 */
	public void setAnalyzeUserName(String analyzeUserName) {
		this.analyzeUserName = analyzeUserName;
	}

	/**
	 * @return the analyzeDate
	 */
	public Date getAnalyzeDate() {
		return analyzeDate;
	}

	/**
	 * @param analyzeDate the analyzeDate to set
	 */
	public void setAnalyzeDate(Date analyzeDate) {
		this.analyzeDate = analyzeDate;
	}

	/**
	 * @return the closeUser
	 */
	public String getCloseUser() {
		return closeUser;
	}

	/**
	 * @param closeUser the closeUser to set
	 */
	public void setCloseUser(String closeUser) {
		this.closeUser = closeUser;
	}

	/**
	 * @return the closeUserName
	 */
	public String getCloseUserName() {
		return closeUserName;
	}

	/**
	 * @param closeUserName the closeUserName to set
	 */
	public void setCloseUserName(String closeUserName) {
		this.closeUserName = closeUserName;
	}

	/**
	 * @return the installedDeptId
	 */
	public String getInstalledDeptId() {
		return installedDeptId;
	}

	/**
	 * @param installedDeptId the installedDeptId to set
	 */
	public void setInstalledDeptId(String installedDeptId) {
		this.installedDeptId = installedDeptId;
	}

	/**
	 * @return the installedUser
	 */
	public String getInstalledUser() {
		return installedUser;
	}

	/**
	 * @param installedUser the installedUser to set
	 */
	public void setInstalledUser(String installedUser) {
		this.installedUser = installedUser;
	}

	/**
	 * @return the isTms
	 */
	public String getIsTms() {
		return isTms;
	}

	/**
	 * @param isTms the isTms to set
	 */
	public void setIsTms(String isTms) {
		this.isTms = isTms;
	}

	/**
	 * @return the problemReason
	 */
	public String getProblemReason() {
		return problemReason;
	}

	/**
	 * @param problemReason the problemReason to set
	 */
	public void setProblemReason(String problemReason) {
		this.problemReason = problemReason;
	}

	/**
	 * @return the problemSolution
	 */
	public String getProblemSolution() {
		return problemSolution;
	}

	/**
	 * @param problemSolution the problemSolution to set
	 */
	public void setProblemSolution(String problemSolution) {
		this.problemSolution = problemSolution;
	}

	/**
	 * @return the responsibity
	 */
	public String getResponsibity() {
		return responsibity;
	}

	/**
	 * @param responsibity the responsibity to set
	 */
	public void setResponsibity(String responsibity) {
		this.responsibity = responsibity;
	}

	/**
	 * @return the isBussinessAddress
	 */
	public String getIsBussinessAddress() {
		return isBussinessAddress;
	}

	/**
	 * @param isBussinessAddress the isBussinessAddress to set
	 */
	public void setIsBussinessAddress(String isBussinessAddress) {
		this.isBussinessAddress = isBussinessAddress;
	}

	/**
	 * @return the isBussinessContact
	 */
	public String getIsBussinessContact() {
		return isBussinessContact;
	}

	/**
	 * @param isBussinessContact the isBussinessContact to set
	 */
	public void setIsBussinessContact(String isBussinessContact) {
		this.isBussinessContact = isBussinessContact;
	}

	/**
	 * @return the isBussinessContactPhone
	 */
	public String getIsBussinessContactPhone() {
		return isBussinessContactPhone;
	}

	/**
	 * @param isBussinessContactPhone the isBussinessContactPhone to set
	 */
	public void setIsBussinessContactPhone(String isBussinessContactPhone) {
		this.isBussinessContactPhone = isBussinessContactPhone;
	}

	/**
	 * @return the contactIsBussinessAddress
	 */
	public String getContactIsBussinessAddress() {
		return contactIsBussinessAddress;
	}

	/**
	 * @param contactIsBussinessAddress the contactIsBussinessAddress to set
	 */
	public void setContactIsBussinessAddress(String contactIsBussinessAddress) {
		this.contactIsBussinessAddress = contactIsBussinessAddress;
	}

	/**
	 * @return the contactIsBussinessContact
	 */
	public String getContactIsBussinessContact() {
		return contactIsBussinessContact;
	}

	/**
	 * @param contactIsBussinessContact the contactIsBussinessContact to set
	 */
	public void setContactIsBussinessContact(String contactIsBussinessContact) {
		this.contactIsBussinessContact = contactIsBussinessContact;
	}

	/**
	 * @return the contactIsBussinessContactPhone
	 */
	public String getContactIsBussinessContactPhone() {
		return contactIsBussinessContactPhone;
	}

	/**
	 * @param contactIsBussinessContactPhone the contactIsBussinessContactPhone to set
	 */
	public void setContactIsBussinessContactPhone(String contactIsBussinessContactPhone) {
		this.contactIsBussinessContactPhone = contactIsBussinessContactPhone;
	}

	/**
	 * @return the responseWarnning
	 */
	public Double getResponseWarnning() {
		return responseWarnning;
	}

	/**
	 * @param responseWarnning the responseWarnning to set
	 */
	public void setResponseWarnning(Double responseWarnning) {
		this.responseWarnning = responseWarnning;
	}

	/**
	 * @return the arriveWarnning
	 */
	public Double getArriveWarnning() {
		return arriveWarnning;
	}

	/**
	 * @param arriveWarnning the arriveWarnning to set
	 */
	public void setArriveWarnning(Double arriveWarnning) {
		this.arriveWarnning = arriveWarnning;
	}

	/**
	 * @return the completeWarnning
	 */
	public Double getCompleteWarnning() {
		return completeWarnning;
	}

	/**
	 * @param completeWarnning the completeWarnning to set
	 */
	public void setCompleteWarnning(Double completeWarnning) {
		this.completeWarnning = completeWarnning;
	}

	/**
	 * @return the installedDate
	 */
	public Date getInstalledDate() {
		return installedDate;
	}

	/**
	 * @param installedDate the installedDate to set
	 */
	public void setInstalledDate(Date installedDate) {
		this.installedDate = installedDate;
	}

	/**
	 * @return the uninstalledDate
	 */
	public Date getUninstalledDate() {
		return uninstalledDate;
	}

	/**
	 * @param uninstalledDate the uninstalledDate to set
	 */
	public void setUninstalledDate(Date uninstalledDate) {
		this.uninstalledDate = uninstalledDate;
	}

	/**
	 * @return the cupEnableDate
	 */
	public Date getCupEnableDate() {
		return cupEnableDate;
	}

	/**
	 * @param cupEnableDate the cupEnableDate to set
	 */
	public void setCupEnableDate(Date cupEnableDate) {
		this.cupEnableDate = cupEnableDate;
	}

	/**
	 * @return the cupDisableDate
	 */
	public Date getCupDisableDate() {
		return cupDisableDate;
	}

	/**
	 * @param cupDisableDate the cupDisableDate to set
	 */
	public void setCupDisableDate(Date cupDisableDate) {
		this.cupDisableDate = cupDisableDate;
	}

	/**
	 * @return the updateItem
	 */
	public String getUpdateItem() {
		return updateItem;
	}

	/**
	 * @param updateItem the updateItem to set
	 */
	public void setUpdateItem(String updateItem) {
		this.updateItem = updateItem;
	}

	/**
	 * @return the problemReasonCode
	 */
	public String getProblemReasonCode() {
		return problemReasonCode;
	}

	/**
	 * @param problemReasonCode the problemReasonCode to set
	 */
	public void setProblemReasonCode(String problemReasonCode) {
		this.problemReasonCode = problemReasonCode;
	}

	/**
	 * @return the problemSolutionCode
	 */
	public String getProblemSolutionCode() {
		return problemSolutionCode;
	}

	/**
	 * @param problemSolutionCode the problemSolutionCode to set
	 */
	public void setProblemSolutionCode(String problemSolutionCode) {
		this.problemSolutionCode = problemSolutionCode;
	}
	/**
	 * @return the electronicInvoice
	 */
	public String getElectronicInvoice() {
		return electronicInvoice;
	}

	/**
	 * @param electronicInvoice the electronicInvoice to set
	 */
	public void setElectronicInvoice(String electronicInvoice) {
		this.electronicInvoice = electronicInvoice;
	}
	/**
	 * @return the cupQuickPass
	 */
	public String getCupQuickPass() {
		return cupQuickPass;
	}

	/**
	 * @param cupQuickPass the cupQuickPass to set
	 */
	public void setCupQuickPass(String cupQuickPass) {
		this.cupQuickPass = cupQuickPass;
	}

	/**
	 * @return the sameInstalled
	 */
	public String getSameInstalled() {
		return sameInstalled;
	}

	/**
	 * @param sameInstalled the sameInstalled to set
	 */
	public void setSameInstalled(String sameInstalled) {
		this.sameInstalled = sameInstalled;
	}

	/**
	 * @return the tmsParamDesc
	 */
	public String getTmsParamDesc() {
		return tmsParamDesc;
	}

	/**
	 * @param tmsParamDesc the tmsParamDesc to set
	 */
	public void setTmsParamDesc(String tmsParamDesc) {
		this.tmsParamDesc = tmsParamDesc;
	}

	/**
	 * @return the fomsCase
	 */
	public String getFomsCase() {
		return fomsCase;
	}

	/**
	 * @param fomsCase the fomsCase to set
	 */
	public void setFomsCase(String fomsCase) {
		this.fomsCase = fomsCase;
	}

	/**
	 * @return the isFirstInstalled
	 */
	public String getIsFirstInstalled() {
		return isFirstInstalled;
	}

	/**
	 * @param isFirstInstalled the isFirstInstalled to set
	 */
	public void setIsFirstInstalled(String isFirstInstalled) {
		this.isFirstInstalled = isFirstInstalled;
	}

	/**
	 * @return the logoStyle
	 */
	public String getLogoStyle() {
		return logoStyle;
	}

	/**
	 * @return the isOpenEncrypt
	 */
	public String getIsOpenEncrypt() {
		return isOpenEncrypt;
	}

	/**
	 * @return the electronicPayPlatform
	 */
	public String getElectronicPayPlatform() {
		return electronicPayPlatform;
	}

	/**
	 * @param logoStyle the logoStyle to set
	 */
	public void setLogoStyle(String logoStyle) {
		this.logoStyle = logoStyle;
	}

	/**
	 * @param isOpenEncrypt the isOpenEncrypt to set
	 */
	public void setIsOpenEncrypt(String isOpenEncrypt) {
		this.isOpenEncrypt = isOpenEncrypt;
	}

	/**
	 * @param electronicPayPlatform the electronicPayPlatform to set
	 */
	public void setElectronicPayPlatform(String electronicPayPlatform) {
		this.electronicPayPlatform = electronicPayPlatform;
	}

	/**
	 * @return the completeDepartmentId
	 */
	public String getCompleteDepartmentId() {
		return completeDepartmentId;
	}

	/**
	 * @param completeDepartmentId the completeDepartmentId to set
	 */
	public void setCompleteDepartmentId(String completeDepartmentId) {
		this.completeDepartmentId = completeDepartmentId;
	}

	/**
	 * @return the hasOnlineExclusion
	 */
	public String getHasOnlineExclusion() {
		return hasOnlineExclusion;
	}

	/**
	 * @param hasOnlineExclusion the hasOnlineExclusion to set
	 */
	public void setHasOnlineExclusion(String hasOnlineExclusion) {
		this.hasOnlineExclusion = hasOnlineExclusion;
	}

	/**
	 * @return the firstDescription
	 */
	public String getFirstDescription() {
		return firstDescription;
	}

	/**
	 * @param firstDescription the firstDescription to set
	 */
	public void setFirstDescription(String firstDescription) {
		this.firstDescription = firstDescription;
	}

	/**
	 * @return the secondDescription
	 */
	public String getSecondDescription() {
		return secondDescription;
	}

	/**
	 * @param secondDescription the secondDescription to set
	 */
	public void setSecondDescription(String secondDescription) {
		this.secondDescription = secondDescription;
	}

	/**
	 * @return the thirdDescription
	 */
	public String getThirdDescription() {
		return thirdDescription;
	}

	/**
	 * @param thirdDescription the thirdDescription to set
	 */
	public void setThirdDescription(String thirdDescription) {
		this.thirdDescription = thirdDescription;
	}

	/**
	 * @return the hasRetreat
	 */
	public String getHasRetreat() {
		return hasRetreat;
	}

	/**
	 * @param hasRetreat the hasRetreat to set
	 */
	public void setHasRetreat(String hasRetreat) {
		this.hasRetreat = hasRetreat;
	}

	/**
	 * @return the hasDelay
	 */
	public String getHasDelay() {
		return hasDelay;
	}

	/**
	 * @param hasDelay the hasDelay to set
	 */
	public void setHasDelay(String hasDelay) {
		this.hasDelay = hasDelay;
	}

	/**
	 * @return the isBussinessContactEmail
	 */
	public String getIsBussinessContactEmail() {
		return isBussinessContactEmail;
	}

	/**
	 * @param isBussinessContactEmail the isBussinessContactEmail to set
	 */
	public void setIsBussinessContactEmail(String isBussinessContactEmail) {
		this.isBussinessContactEmail = isBussinessContactEmail;
	}

	/**
	 * @return the installedContactMobilePhone
	 */
	public String getInstalledContactMobilePhone() {
		return installedContactMobilePhone;
	}

	/**
	 * @param installedContactMobilePhone the installedContactMobilePhone to set
	 */
	public void setInstalledContactMobilePhone(String installedContactMobilePhone) {
		this.installedContactMobilePhone = installedContactMobilePhone;
	}

	/**
	 * @return the installedContactEmail
	 */
	public String getInstalledContactEmail() {
		return installedContactEmail;
	}

	/**
	 * @param installedContactEmail the installedContactEmail to set
	 */
	public void setInstalledContactEmail(String installedContactEmail) {
		this.installedContactEmail = installedContactEmail;
	}

	/**
	 * @return the contactIsBussinessContactMobilePhone
	 */
	public String getContactIsBussinessContactMobilePhone() {
		return contactIsBussinessContactMobilePhone;
	}

	/**
	 * @param contactIsBussinessContactMobilePhone the contactIsBussinessContactMobilePhone to set
	 */
	public void setContactIsBussinessContactMobilePhone(
			String contactIsBussinessContactMobilePhone) {
		this.contactIsBussinessContactMobilePhone = contactIsBussinessContactMobilePhone;
	}

	/**
	 * @return the contactIsBussinessContactEmail
	 */
	public String getContactIsBussinessContactEmail() {
		return contactIsBussinessContactEmail;
	}

	/**
	 * @param contactIsBussinessContactEmail the contactIsBussinessContactEmail to set
	 */
	public void setContactIsBussinessContactEmail(
			String contactIsBussinessContactEmail) {
		this.contactIsBussinessContactEmail = contactIsBussinessContactEmail;
	}

	/**
	 * @return the contactMobilePhone
	 */
	public String getContactMobilePhone() {
		return contactMobilePhone;
	}

	/**
	 * @param contactMobilePhone the contactMobilePhone to set
	 */
	public void setContactMobilePhone(String contactMobilePhone) {
		this.contactMobilePhone = contactMobilePhone;
	}

	/**
	 * @return the contactUserEmail
	 */
	public String getContactUserEmail() {
		return contactUserEmail;
	}

	/**
	 * @param contactUserEmail the contactUserEmail to set
	 */
	public void setContactUserEmail(String contactUserEmail) {
		this.contactUserEmail = contactUserEmail;
	}

	/**
	 * @return the cmsCase
	 */
	public String getCmsCase() {
		return cmsCase;
	}

	/**
	 * @param cmsCase the cmsCase to set
	 */
	public void setCmsCase(String cmsCase) {
		this.cmsCase = cmsCase;
	}

	/**
	 * @return the isBussinessContactMobilePhone
	 */
	public String getIsBussinessContactMobilePhone() {
		return isBussinessContactMobilePhone;
	}

	/**
	 * @param isBussinessContactMobilePhone the isBussinessContactMobilePhone to set
	 */
	public void setIsBussinessContactMobilePhone(
			String isBussinessContactMobilePhone) {
		this.isBussinessContactMobilePhone = isBussinessContactMobilePhone;
	}

	/**
	 * @return the installCaseId
	 */
	public String getInstallCaseId() {
		return installCaseId;
	}

	/**
	 * @param installCaseId the installCaseId to set
	 */
	public void setInstallCaseId(String installCaseId) {
		this.installCaseId = installCaseId;
	}

	/**
	 * @return the installCompleteDate
	 */
	public Date getInstallCompleteDate() {
		return installCompleteDate;
	}

	/**
	 * @param installCompleteDate the installCompleteDate to set
	 */
	public void setInstallCompleteDate(Date installCompleteDate) {
		this.installCompleteDate = installCompleteDate;
	}

	/**
	 * @return the installedPostCode
	 */
	public String getInstalledPostCode() {
		return installedPostCode;
	}

	/**
	 * @param installedPostCode the installedPostCode to set
	 */
	public void setInstalledPostCode(String installedPostCode) {
		this.installedPostCode = installedPostCode;
	}

	/**
	 * @return the contactPostCode
	 */
	public String getContactPostCode() {
		return contactPostCode;
	}

	/**
	 * @param contactPostCode the contactPostCode to set
	 */
	public void setContactPostCode(String contactPostCode) {
		this.contactPostCode = contactPostCode;
	}

	/**
	 * @return the logisticsVendor
	 */
	public String getLogisticsVendor() {
		return logisticsVendor;
	}

	/**
	 * @param logisticsVendor the logisticsVendor to set
	 */
	public void setLogisticsVendor(String logisticsVendor) {
		this.logisticsVendor = logisticsVendor;
	}

	/**
	 * @return the logisticsNumber
	 */
	public String getLogisticsNumber() {
		return logisticsNumber;
	}

	/**
	 * @param logisticsNumber the logisticsNumber to set
	 */
	public void setLogisticsNumber(String logisticsNumber) {
		this.logisticsNumber = logisticsNumber;
	}

	/**
	 * @return the receiptType
	 */
	public String getReceiptType() {
		return receiptType;
	}

	/**
	 * @param receiptType the receiptType to set
	 */
	public void setReceiptType(String receiptType) {
		this.receiptType = receiptType;
	}
	
}