package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmCaseAttFileDTO;

/**
 * SrmHistoryCaseAttFile generated by hbm2java
 */
public class SrmHistoryCaseAttFile extends DomainModelObject<String, SrmCaseAttFileDTO>{

	private String attFileId;
	private String caseId;
	private String fileName;
	private String filePath;
	private String createdById;
	private String createdByName;
	private Date createdDate;

	public SrmHistoryCaseAttFile() {
	}

	public SrmHistoryCaseAttFile(String attFileId) {
		this.attFileId = attFileId;
	}

	public SrmHistoryCaseAttFile(String attFileId,
			String caseId, String fileName,
			String filePath, String createdById,
			String createdByName) {
		this.attFileId = attFileId;
		this.caseId = caseId;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
	}

	public String getAttFileId() {
		return this.attFileId;
	}

	public void setAttFileId(String attFileId) {
		this.attFileId = attFileId;
	}	

	public String getCaseId() {
		return caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
