package com.cybersoft4u.xian.iatoms.services.dmo;

import java.util.Date;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmPaymentItemDTO;

import cafe.core.dmo.DomainModelObject;

/**
 * SrmPaymentItem generated by hbm2java
 */
public class SrmPaymentItem extends DomainModelObject<String, SrmPaymentItemDTO>{

	private String itemId;
	private String paymentId;
	private String status;
	private String backDesc;
	private String paymentItem;
	private String itemName;
	private String serialNumber;
	private String contractId;
	private String suppliesType;
	private Integer suppliesAmount;
	private String isPay = "N";
	private String paymentReason;
	private String reasonDetail;
	private String checkResult;
	private String checkUser;
	private String fee;
	private String feeDesc;
	private String isAskPay = "N";
	private String paymentType;
	private String paymentTypeDesc;
	private Date askPayDate;
	private String askPayDesc;
	private Date cancelDate;
	private Date repaymentDate;
	private String cancelDesc;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;
	private Date lockedDate;
	

	public SrmPaymentItem() {
	}

	public SrmPaymentItem(String itemId) {
		this.itemId = itemId;
	}

	public SrmPaymentItem(String itemId, String paymentId, String status,
			String backDesc, String paymentItem, String itemName,
			String serialNumber, String contractId, String suppliesType,
			Integer suppliesAmount, String isPay, String paymentReason,
			String reasonDetail, String checkResult, String checkUser,
			String fee, String feeDesc, String isAskPay, String paymentType,
			String paymentTypeDesc, Date askPayDate, String askPayDesc,
			Date cancelDate, Date repaymentDate, String cancelDesc,
			String updatedById, String updatedByName, Date updatedDate,
			Date lockedDate) {
		this.itemId = itemId;
		this.paymentId = paymentId;
		this.status = status;
		this.backDesc = backDesc;
		this.paymentItem = paymentItem;
		this.itemName = itemName;
		this.serialNumber = serialNumber;
		this.contractId = contractId;
		this.suppliesType = suppliesType;
		this.suppliesAmount = suppliesAmount;
		this.isPay = isPay;
		this.paymentReason = paymentReason;
		this.reasonDetail = reasonDetail;
		this.checkResult = checkResult;
		this.checkUser = checkUser;
		this.fee = fee;
		this.feeDesc = feeDesc;
		this.isAskPay = isAskPay;
		this.paymentType = paymentType;
		this.paymentTypeDesc = paymentTypeDesc;
		this.askPayDate = askPayDate;
		this.askPayDesc = askPayDesc;
		this.cancelDate = cancelDate;
		this.repaymentDate = repaymentDate;
		this.cancelDesc = cancelDesc;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.lockedDate = lockedDate;
	}

	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}	

	public String getPaymentId() {
		return paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBackDesc() {
		return backDesc;
	}

	public void setBackDesc(String backDesc) {
		this.backDesc = backDesc;
	}

	public String getPaymentItem() {
		return this.paymentItem;
	}

	public void setPaymentItem(String paymentItem) {
		this.paymentItem = paymentItem;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getSuppliesType() {
		return this.suppliesType;
	}

	public void setSuppliesType(String suppliesType) {
		this.suppliesType = suppliesType;
	}

	public Integer getSuppliesAmount() {
		return this.suppliesAmount;
	}

	public void setSuppliesAmount(Integer suppliesAmount) {
		this.suppliesAmount = suppliesAmount;
	}

	public String getIsPay() {
		return this.isPay;
	}

	public void setIsPay(String isPay) {
		this.isPay = isPay;
	}

	public String getPaymentReason() {
		return this.paymentReason;
	}

	public void setPaymentReason(String paymentReason) {
		this.paymentReason = paymentReason;
	}

	public String getReasonDetail() {
		return this.reasonDetail;
	}

	public void setReasonDetail(String reasonDetail) {
		this.reasonDetail = reasonDetail;
	}

	public String getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	public String getCheckUser() {
		return this.checkUser;
	}

	public void setCheckUser(String checkUser) {
		this.checkUser = checkUser;
	}

	public String getFee() {
		return this.fee;
	}

	public void setFee(String fee) {
		this.fee = fee;
	}

	public String getFeeDesc() {
		return this.feeDesc;
	}

	public void setFeeDesc(String feeDesc) {
		this.feeDesc = feeDesc;
	}

	public String getIsAskPay() {
		return this.isAskPay;
	}

	public void setIsAskPay(String isAskPay) {
		this.isAskPay = isAskPay;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public String getPaymentTypeDesc() {
		return this.paymentTypeDesc;
	}

	public void setPaymentTypeDesc(String paymentTypeDesc) {
		this.paymentTypeDesc = paymentTypeDesc;
	}

	public Date getAskPayDate() {
		return this.askPayDate;
	}

	public void setAskPayDate(Date askPayDate) {
		this.askPayDate = askPayDate;
	}

	public String getAskPayDesc() {
		return this.askPayDesc;
	}

	public void setAskPayDesc(String askPayDesc) {
		this.askPayDesc = askPayDesc;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	public Date getRepaymentDate() {
		return this.repaymentDate;
	}

	public void setRepaymentDate(Date repaymentDate) {
		this.repaymentDate = repaymentDate;
	}

	public String getCancelDesc() {
		return this.cancelDesc;
	}

	public void setCancelDesc(String cancelDesc) {
		this.cancelDesc = cancelDesc;
	}

	public String getUpdatedById() {
		return this.updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the lockedDate
	 */
	public Date getLockedDate() {
		return lockedDate;
	}

	/**
	 * @param lockedDate the lockedDate to set
	 */
	public void setLockedDate(Date lockedDate) {
		this.lockedDate = lockedDate;
	}

}
