package com.cybersoft4u.xian.iatoms.services.dmo;

// Generated 2017/2/9 �W�� 10:18:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmPaymentInfoDTO;

import cafe.core.dmo.DomainModelObject;

/**
 * SrmPaymentInfo generated by hbm2java
 */
public class SrmPaymentInfo extends DomainModelObject<String, SrmPaymentInfoDTO>{

	private String paymentId;
	private String customerId;
	private String dtid;
	private String requirementNo;
	private String caseId;
	private String tid;
	private String merchantId;
	private Date realFinishDate;
	private Date caseCreatedDate;	
	private String createdById;
	private String createdByName;
	private Date createdDate;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;
	private String merchantHeaderId;
	private String isCaseCreate = "N";

	public SrmPaymentInfo() {
	}

	public SrmPaymentInfo(String paymentId) {
		this.paymentId = paymentId;
	}

	public SrmPaymentInfo(String paymentId, String customerId, String dtid,
			String requirementNo, String caseId, String tid, String merchantId,
			Date realFinishDate, Date caseCreatedDate, String merchantHeaderId,
			String createdById, String createdByName, Date createdDate,
			String updatedById, String updatedByName, Date updatedDate, String isCaseCreate) {
		this.paymentId = paymentId;
		this.customerId = customerId;
		this.dtid = dtid;
		this.requirementNo = requirementNo;
		this.caseId = caseId;
		this.tid = tid;
		this.merchantId = merchantId;
		this.realFinishDate = realFinishDate;
		this.caseCreatedDate = caseCreatedDate;
		this.createdById = createdById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.merchantHeaderId = merchantHeaderId;
		this.isCaseCreate = isCaseCreate;
	}

	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getDtid() {
		return this.dtid;
	}

	public void setDtid(String dtid) {
		this.dtid = dtid;
	}

	public String getRequirementNo() {
		return this.requirementNo;
	}

	public void setRequirementNo(String requirementNo) {
		this.requirementNo = requirementNo;
	}

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	public Date getRealFinishDate() {
		return this.realFinishDate;
	}

	public void setRealFinishDate(Date realFinishDate) {
		this.realFinishDate = realFinishDate;
	}

	public Date getCaseCreatedDate() {
		return this.caseCreatedDate;
	}

	public void setCaseCreatedDate(Date caseCreatedDate) {
		this.caseCreatedDate = caseCreatedDate;
	}

	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedById() {
		return this.updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the merchantHeaderId
	 */
	public String getMerchantHeaderId() {
		return merchantHeaderId;
	}

	/**
	 * @param merchantHeaderId the merchantHeaderId to set
	 */
	public void setMerchantHeaderId(String merchantHeaderId) {
		this.merchantHeaderId = merchantHeaderId;
	}

	/**
	 * @return the isCaseCreate
	 */
	public String getIsCaseCreate() {
		return isCaseCreate;
	}

	/**
	 * @param isCaseCreate the isCaseCreate to set
	 */
	public void setIsCaseCreate(String isCaseCreate) {
		this.isCaseCreate = isCaseCreate;
	}
	
}
