package com.cybersoft4u.xian.iatoms.services.dmo;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmQueryTemplateDTO;

import cafe.core.dmo.DomainModelObject;

// Generated 2017/2/24 �U�� 01:13:23 by Hibernate Tools 3.4.0.CR1

/**
 * SrmCaseAssetFunction generated by hbm2java
 */
public class SrmQueryTemplate extends DomainModelObject<String, SrmQueryTemplateDTO>{

	private String templateId;
	private String templateName;
	private String userId;
	private String fieldContent;
	private String isDefault = "N";
	
	public SrmQueryTemplate() {
	}

	public SrmQueryTemplate(String templateId, String templateName, String userId, String fieldContent,
			String isDefault) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.userId = userId;
		this.fieldContent = fieldContent;
		this.isDefault = isDefault;
	}

	/**
	 * @return the templateId
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * @param templateId the templateId to set
	 */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * @return the fieldContent
	 */
	public String getFieldContent() {
		return fieldContent;
	}

	/**
	 * @param fieldContent the fieldContent to set
	 */
	public void setFieldContent(String fieldContent) {
		this.fieldContent = fieldContent;
	}

	/**
	 * @return the templateName
	 */
	public String getTemplateName() {
		return templateName;
	}

	/**
	 * @param templateName the templateName to set
	 */
	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	/**
	 * @return the isDefault
	 */
	public String getIsDefault() {
		return isDefault;
	}

	/**
	 * @param isDefault the isDefault to set
	 */
	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}
	
}
