package com.cybersoft4u.xian.iatoms.services.dmo;

import java.util.Date;

// Generated 2016/12/7 �U�� 02:32:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import cafe.core.dmo.DomainModelObject;

import com.cybersoft4u.xian.iatoms.common.bean.dto.SrmTransactionParameterItemDTO;

/**
 * SrmTransactionParameterItem generated by hbm2java
 */
public class SrmTransactionParameterItem extends DomainModelObject<String, SrmTransactionParameterItemDTO>{

	private String paramterItemId;
	private String paramterItemCode;
	private String paramterItemName;
	private String paramterItemType;
	private String paramterDataType;
	private Integer paramterItemLength;
	private Integer itemOrder;
	private Date effectiveDate;
	private String approvedFlag;

	public SrmTransactionParameterItem() {
	}

	public SrmTransactionParameterItem(String paramterItemId) {
		this.paramterItemId = paramterItemId;
	}

	public SrmTransactionParameterItem(String paramterItemId,
			String paramterItemCode, String paramterItemName,
			String paramterItemType, String paramterDataType,Integer paramterItemLength, Integer itemOrder,
			Date effectiveDate, String approvedFlag) {
		this.paramterItemId = paramterItemId;
		this.paramterItemCode = paramterItemCode;
		this.paramterItemName = paramterItemName;
		this.paramterItemType = paramterItemType;
		this.paramterDataType = paramterDataType;
		this.paramterItemLength = paramterItemLength;
		this.itemOrder = itemOrder;
		this.effectiveDate = effectiveDate;
		this.approvedFlag = approvedFlag;
	}

	public String getParamterItemId() {
		return this.paramterItemId;
	}

	public void setParamterItemId(String paramterItemId) {
		this.paramterItemId = paramterItemId;
	}

	public String getParamterItemCode() {
		return this.paramterItemCode;
	}

	public void setParamterItemCode(String paramterItemCode) {
		this.paramterItemCode = paramterItemCode;
	}

	public String getParamterItemName() {
		return this.paramterItemName;
	}

	public void setParamterItemName(String paramterItemName) {
		this.paramterItemName = paramterItemName;
	}

	public String getParamterItemType() {
		return this.paramterItemType;
	}

	public void setParamterItemType(String paramterItemType) {
		this.paramterItemType = paramterItemType;
	}

	/**
	 * @return the paramterDataType
	 */
	public String getParamterDataType() {
		return paramterDataType;
	}

	/**
	 * @param paramterDataType the paramterDataType to set
	 */
	public void setParamterDataType(String paramterDataType) {
		this.paramterDataType = paramterDataType;
	}

	public Integer getParamterItemLength() {
		return this.paramterItemLength;
	}

	public void setParamterItemLength(Integer paramterItemLength) {
		this.paramterItemLength = paramterItemLength;
	}
	public Integer getItemOrder() {
		return this.itemOrder;
	}

	public void setItemOrder(Integer itemOrder) {
		this.itemOrder = itemOrder;
	}

	/**
	 * @return the effectiveDate
	 */
	public Date getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * @param effectiveDate the effectiveDate to set
	 */
	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * @return the approvedFlag
	 */
	public String getApprovedFlag() {
		return approvedFlag;
	}

	/**
	 * @param approvedFlag the approvedFlag to set
	 */
	public void setApprovedFlag(String approvedFlag) {
		this.approvedFlag = approvedFlag;
	}
}
