package com.cybersoft4u.xian.iatoms.common.bean.dto;

import cafe.workflow.bean.dto.AbstractCaseDetailDTO;
import cafe.workflow.dmo.CaseTransaction;
/**
 * CaseDetail generated by hbm2java
 */
public class CaseDetailDTO extends  AbstractCaseDetailDTO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5758687006071029289L;
	private String caseType;
	private CaseTransaction caseTransaction;
	/**
	 * @return the caseTransaction
	 */
	public CaseTransaction getCaseTransaction() {
		return caseTransaction;
	}

	/**
	 * @param caseTransaction the caseTransaction to set
	 */
	public void setCaseTransaction(CaseTransaction caseTransaction) {
		this.caseTransaction = caseTransaction;
	}

	public CaseDetailDTO() {
	}

	public CaseDetailDTO(String id, String caseType, String processId) {
		this.id = id;
		this.caseType = caseType;
		this.setProcessId(processId);
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}
}
